### ISSUE TITLE
Twitch Chat Improvement Suggestion

### ISSUE THREAD

**Issue by hakuame** [alamminsalo/orion#10]
ME Again :D !
Just wondering will the twitch chat of orion show the emotes instead of texts in the future versions?
It will be great if this feature is adding or planning to add to the app.
Thank you for putting so many efforts to it and listening to the users' suggestions.

**Comment by b3visund3ad** [comment]
My request/suggestion, take notes from bttv but make it awesome :) I am loving this program so far.

**Comment by alamminsalo** [comment]
This is doable, not very high on priority list but I'll look onto this when I have more time

**Comment by ahjolinna** [comment]
I like to add here the option to open links and maybe name/viewer-list

**Comment by ahjolinna** [comment]
@alamminsalo : I don't know if you have checked this already but the [sailfishOS twitch app's](https://github.com/Aldrog/TwitchTube) chat part doesn't require libcommuni to work (its Qt5 only), so I was wondering if that implementation could work better than relying on libcommuni?

**Comment by alamminsalo** [comment]
@ahjolinna This is doable. Needs some prototyping but would be probably more efficient than requiring libcommuni

**Comment by alamminsalo** [comment]
Okay, in the **dev** there's now an implementation which uses the sailfish twitch app's (heavily simplified) code for chat.

**Comment by ahjolinna** [comment]
one bug found, if there is a HUGE spam or the chat goes too fast, it seems it just gives up and stops "scrolling" you have to scroll yourself

and it still doesn't allow open links nor show emoticons

so the same problems what was in libcommuni :D

**Comment by alamminsalo** [comment]
Yeah, the thing with the emoticons is that they need to be implemented into the qml view so it's not in the backend...

**Comment by ahjolinna** [comment]
okay, so it the same thing with links? will it be hard to implement

anyway I don't know if u have any intrested but, maybe adding [vod chat replay](https://help.twitch.tv/customer/portal/articles/2337148-chat-replay-faq) support? it seems to pickup something but doesnt work completely (aka I got some one random)

**Comment by alamminsalo** [comment]
I put a fix regarding the chat scroll bug just now. It causes a bit "stickiness" when starting to scroll upwards from the chat bottom, but seems to work more reliably than before

**Comment by alamminsalo** [comment]
I just added clickable urls to the chat

**Comment by ahjolinna** [comment]
sigh, :D the chat scroll bug is still there at times.. I wonder why it has problems with it -_-

I did notice on patern, if someone did a chat bot command like "!uptime" or something like that it will stop scrolling, so for some reason when the chat bot says something it doesnt show up and u have to scroll manually...

...hmm I just notice when I was writing that the "bug" happend on one channel but not on another one, it seems little bit inconsistent ...

btw. what font does the chat use? is it DroidSans? if so, could it be possible for it to use systems font, I personally love [Adobes Source Sans Pro](http://adobe-fonts.github.io/source-sans-pro/) font (I notice that even jolla uses it on SailfishOS)

PS. about the link thing, it works if there is http(s):// but not if there is www. solely

**Comment by ahjolinna** [comment]
now I get this error spam: 
`qrc:/irc/ChatView.qml:157: TypeError: Property 'remove' of object  QuickListView_QML_60(0x555555f1a670) is not a function`

**Comment by alamminsalo** [comment]
> qrc:/irc/ChatView.qml:157: TypeError: Property 'remove' of object QuickListView_QML_60(0x555555f1a670) is not a function
Fixed.

**Comment by ahjolinna** [comment]
kiitos, that was fast..anyway...

there is small "visual glitch" in the chat, that also could cause the scrolling issue at times...sometimes you only see part of the conversation half of the text what the person has written, aka it doesn't update/scroll it completely..it's rare but it has happened at times

**Comment by alamminsalo** [comment]
alright, on the dev branch there is now a fix (to scrolling issue). Also anonymous chat is now implemented. Let me know if you STILL encounter any weird behavior/scroll drops

**Comment by ahjolinna** [comment]
okay the chat seems to ...almost work; it seems like the basic "scroll issue" happens now only with the first time you load the a stream/chat but after that with others I haven't notice any other problems than when chat is starting to "fill up" the chat & video playback start to have problems*...maybe it has to do with ram is filling up, about in 200mb it started to have problems. Maybe limiting the chat history to some max value could help.

*the chat is slow and cant scroll, plus the video playback has a lot of problem with buffering (Warning: "A lot of buffers are being dropped.")

**Comment by alamminsalo** [comment]
Okay... the chat currently has limit of 1000 but since the addition of urls I guess it became much more heavy on resources, I'll try for 500

**Comment by ahjolinna** [comment]
that worked somewhat*, it seems after a while (can't say when) the chat just stops loading, but again after about 10min it started again (the playback did freeze for few seconds) with the scolling issue :D 

* orion had almost 300mb of ram usage and it still worked just fine now

**Comment by alamminsalo** [comment]
Yeah, it has around 300 mb of usage when fully loaded (stuff on all search lists, chat is filled (500), and video is on). Possibly even more. Anyway, I put a small fix which should give a small boost to chat performance when nearing 500 messages. It's on `dev` branch

**Comment by ahjolinna** [comment]
se taisi olla siinä, seems to work now. Now just support for emoticons and that should be it :D

**Comment by ahjolinna** [comment]
@alamminsalo : can you move those 2 commits left in dev branch to master?

**Comment by alamminsalo** [comment]
@ahjolinna Yes, it's now merged

**Comment by woowoots** [comment]
would be indeed nice to have somes chat improvement.
- color for pseudo
- maybe like the original twitch chat, a bit more space between each response, its sometime not every easy to follow a discussion since everything is white 

would also indeed love to be able to see the emote.


Hope that software still is in developpment

**Comment by zabuldon** [comment]
@woowoots 
color for pseudo - already implemented
I do not want to colorize full chat output because it can cause hell on the screen.

Regarding a space between messages. I think we can adjust this in future.

**Comment by woowoots** [comment]
@zabuldon  hm, maybe in the github version, but i have no idea how to install that :( 
Any "clear" explanation somewhere for a noob like me to do that ?

**Comment by rakslice** [comment]
This ticket is getting pretty huge... could we split anything not already closable out into separate tickets?

**Comment by ahjolinna** [comment]
I agree with @rakslice I was going to suggest this also...but I notice that everything is done, well more or less...okay the link support thing doesn't work 100% yet
