### ISSUE TITLE
orion creates GPUCache folder  at user home folder on linux

### ISSUE THREAD

**Issue by ahjolinna** [alamminsalo/orion#100]
it seems when you run orion it creates to your home folder an new folder called "GPUCache"  and it has filles called: "data_0" "data_1" "data_2" "data_3" "index" and those files are only 544Kib at size.

this has happened on the both of my distros I use (chakraOS and opensuse)

I had to remove that folder at least ones to resolve my crash issue on chakraOS (https://github.com/alamminsalo/orion/issues/98)...

I don't have a core file from the crash and I can't yet replicate that bug, but I do have the old backtrace:

```
Thread 1 "orion" received signal SIGSEGV, Segmentation fault.
0x00007ffff0772e90 in ?? () from /usr/lib/libQt5Core.so.5
(gdb) bt full
#0  0x00007ffff0772e90 in ?? () from /usr/lib/libQt5Core.so.5
No symbol table info available.
#1  0x000000000044a25b in ?? ()
No symbol table info available.
#2  0x00000000004496f6 in ?? ()
No symbol table info available.
#3  0x000000000043d1dd in ?? ()
No symbol table info available.
#4  0x000000000043e9b4 in ?? ()
No symbol table info available.
#5  0x00000000004429e8 in ?? ()
No symbol table info available.
#6  0x000000000044416f in ?? ()
No symbol table info available.
#7  0x0000000000452e84 in ?? ()
No symbol table info available.
#8  0x00007ffff091fbd1 in QMetaObject::activate(QObject*, int, int, void**) () from /usr/lib/libQt5Core.so.5
No symbol table info available.
#9  0x00007ffff0c34693 in ?? () from /usr/lib/libQt5Network.so.5
No symbol table info available.
#10 0x00007ffff0c3474c in ?? () from /usr/lib/libQt5Network.so.5
No symbol table info available.
#11 0x00007ffff0c3fcb1 in ?? () from /usr/lib/libQt5Network.so.5
No symbol table info available.
#12 0x00007ffff176e9bc in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /usr/lib/libQt5Widgets.so.5
No symbol table info available.
#13 0x00007ffff17763e6 in QApplication::notify(QObject*, QEvent*) () from /usr/lib/libQt5Widgets.so.5
No symbol table info available.
#14 0x00007ffff08f5188 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () from /usr/lib/libQt5Core.so.5
No symbol table info available.
#15 0x00007ffff09493cd in ?? () from /usr/lib/libQt5Core.so.5
No symbol table info available.
#16 0x00007fffeee9afba in g_main_context_dispatch () from /usr/lib/libglib-2.0.so.0
---Type <return> to continue, or q <return> to quit---

```

**Comment by alamminsalo** [comment]
Fixed in 1.5.0-version

**Comment by ahjolinna** [comment]
@alamminsalo : I can confirm this...so does this mean now that  qt5-webengine isn't needed anymore? if so could u update the readme.

what was the reason to move away from  qt5-webengine? ...I know there are some issues with 5.8 (and 5.8.1 wont arrive, Qt group will focus rather on 5.9)

**Comment by alamminsalo** [comment]
The major issue with qt5 webengine was portability. Yes, webengine is no longer needed to build, I'll update the readme tomorrow

**Comment by ahjolinna** [comment]
I wonder why but the playback breaks at time ..the video and audio...I think its a buffering issue (i'm using qt-multimedia); could make a new bug report about that

**Comment by ahjolinna** [comment]
here is one log file that has gdb, Valgrind, and strace output: [orion-logs.txt](https://github.com/alamminsalo/orion/files/926671/orion-logs.txt)

**Comment by ahjolinna** [comment]
I could try mpv-backend instead and see how it works

**Comment by ahjolinna** [comment]
the aur maintainer said that he/she has the same problem and ask if there is a method to enable debugging

**Comment by ahjolinna** [comment]
oh well that ship has sailed...as obs cant build it.....problems with mpv version (seems I need to use community version)
