### ISSUE TITLE
[suggestion] use clazy to check for "inefficient Qt coding mistakes"

### ISSUE THREAD

**Issue by ahjolinna** [alamminsalo/orion#107]
I saw the phoronix news about the new tool from KDE team that checks the Qt code quality, I was thinking this would be useful for orion also, as clazy isn't for KDE usage only it's for all Qt projects...:

> Clazy is a Clang-based static analyzer for Qt that can warn about unnecessary memory allocations, poor API decisions, inefficient usage of some API calls, and more. Additional checks are still being added to Clazy.
> 
> Qt developers wishing to learn more can find out all of the details via this [KDAB blog post](https://www.kdab.com/uncovering-32-qt-best-practices-compile-time-clazy/). The code checker is available via the[ KDE Git repository.](https://github.com/KDE/clazy)

---source [phoronix](http://phoronix.com/scan.php?page=news_item&px=Clang-Clazy-Qt-Slow-Mistakes)

**Comment by ahjolinna** [comment]
@rakslice : have you checked this out as it does work also on windows (and mac).

and if you don't find code optimization important?! this will mean [WAaaGH!!﻿](https://www.youtube.com/watch?v=EQvGuSHMbMc) (DoW3 - Orks Main Theme)

**Comment by rakslice** [comment]
Unfortunately this is a no-go on Windows right now as the Qt 5.8.0 headers break right out of the gate on clang-cl:

```
In file included from release\moc_channelmanager.cpp:9:
In file included from release/../src/model/channelmanager.h:23:
In file included from release/../src/model/imageprovider.h:23:
In file included from I:\qt\5.8\msvc2015_64\include\QtGui\QImage:1:
I:\qt\5.8\msvc2015_64\include\QtGui/qimage.h(280,62):  error: rvalue reference
      to type 'QImage' cannot bind to lvalue of type 'QImage'
        { mirrored_inplace(horizontally, vertically); return qMove(*this); }
                                                             ^~~~~~~~~~~~
I:\qt\5.8\msvc2015_64\include\QtCore/qcompilerdetection.h(1334,18):  note:
      expanded from macro 'qMove'
#define qMove(x) (x)
                 ^~~
```

That appears to be https://bugreports.qt.io/browse/QTBUG-59190 .

I'll try this again once 5.9 is out (or 5.8.1 if they decide to release one).

Also, just so it doesn't go without saying, while static checkers may be a source of easy wins in correctness and performance if they are easy to run and easy to understand identify the relevant results of, if your focus is on performance it is worth considering the usual approach https://en.wikipedia.org/wiki/Program_optimization#When_to_optimize

**Comment by ahjolinna** [comment]
@rakslice : there wont be a 5.8.1, the Qt team said that it will be better to skip it and just focus on 5.9 instead, but the good news is that 5.9 will be released already on 31st May.

Why they wont make 5.8.1? well it seem it was just too broken release ..unfortunately

**Comment by ahjolinna** [comment]
as @rakslice did this at least something with it I think this could be closed ...but it would be nice if clazy would be use once in awhile to check the quality
