### ISSUE TITLE
won't build on Linux -status report

### ISSUE THREAD

**Issue by ahjolinna** [alamminsalo/orion#117]
I will dedicate this at least for [openSUSE (on obs)](https://build.opensuse.org/package/show/home:ahjolinna/orion) and chakraOS [(on ccr)](https://chakralinux.org/ccr/packages.php?ID=7817) build failure reporting ...if @alamminsalo won't mind this...I will keep this open as long there will be many/huge changes this frequently.

as it wont currently build...again :D
[orion-buildlog-20170422.txt](https://github.com/alamminsalo/orion/files/949212/orion-buildlog-20170422.txt)

**Comment by rakslice** [comment]
https://github.com/alamminsalo/orion/pull/118 should fix this.

**Comment by rakslice** [comment]
I've got a branch of https://build.opensuse.org/package/show/home:ahjolinna/orion pointing to a GitHub archive URL so I can just push to the named branch and have it build; I finally got the fork unlinked so I don't have to fire up a VM and use `osc` to resolve conflicts all the time, so I can use it to do test builds conveniently  Hopefully I can find this kind of problem in advance of doing PRs from now on. =)

**Comment by ahjolinna** [comment]
@rakslice : nice, I will at least test chakraOS side as it did compile just fine (without the patch/fix) ..for some reason :D I only now just tested it.

also my current chakraOS machine is my ultrabook and its intel only (ivy bridge)and openSUSE is on my main machine that I will test nvidia side (GTX 970)

PS. one great thing about [OBS](http://openbuildservice.org/) is that it supports so many distros not just opensuse:

![image](https://cloud.githubusercontent.com/assets/6993072/25309089/049f4c60-27cc-11e7-9864-3fe16fd2b566.png)

(also ARCH and kiwi (?) which are missing )

**Comment by ahjolinna** [comment]
well this suck, I can get the "mpv version" to build just fine on manjaro-kde and obs/openSUSE....there is just one big problem with obs/openSUSE version....I cant install it..

I have custom version of openSUSE leap 42.2 with rolling kde/qt (and mesa/xorg) ...and when obs is building it with default leap 42.2 that uses qt5.6 and I have Qt5.8..so I get this error:

```
Problem: orion-20170511-3.1.x86_64 requires libQt5Quick.so.5(Qt_5.6.1_PRIVATE_API)(64bit), but this requirement cannot be provided
  uninstallable providers: libQtQuick5-5.6.1-3.5.x86_64[http-download.opensuse.org-7bb30d1b]
                   libQtQuick5-5.6.1-5.1.x86_64[openSUSE-Leap-42.2_OSS-updates]


for some reason if I go with gst/multimedia backend I don't get this
```

**Comment by ahjolinna** [comment]
@rakslice : any idea how get around this? this is also seems to affect tumbleweed version (rolling release) which uses 5.7.x instead -_-''

I presonally wont care about openSUSE as I will move away from this shit distro in a month or so...I just need to wait for new manjaro-kde or chakraOS ISO that will work for me (https://gitlab.chakralinux.org/tools/chakra-iso/issues/34)

**Comment by rakslice** [comment]
Presumably you need to build the package with the same libraries you want to install it with; I don't know if obs supports mixing releases or if so how it decides which combination of packages that satisify the `BuildRequires` to use, but a local build on a system with the combination of packages you want to use should work.

**Comment by XenonPK** [comment]
Well, at least try to be polite and stop insulting open source projects willy nilly. I'm maintaining an mpv build of orion in OBS without any problem.
Also if you are using the devel obs repos you are bound to have problems (eventually, meaning if something breaks upstream, it will break for you too), as those are untested and are just following upstream development.
You could add your custom repos to your obs build so that it gets linked with Qt 5.8 instead, but i guess insulting the openSUSE project is easier.
Don't take this the wrong way, I'm not against you or anything, It's just that this kind of attitude does not help anyone.

**Comment by XenonPK** [comment]
Btw to add a random obs repo to your build, you would add something like:
`<path project="devel:languages:python" repository="openSUSE_Tumbleweed"/>`
To your project's meta configuration in OBS, replacing `"devel:languages:python"` with the name of the project you want to make available and `"openSUSE_Tumbleweed"` with the name of the distro.

You can see an example [here](https://build.opensuse.org/project/meta/home:xenonpk:python).

**Comment by ahjolinna** [comment]
**_small rant incoming warning_**

@XenonPK : I'm not "insulting" it "willy nilly" as there are many technical and policy problems with openSUSE leap 42.2* compare to other distros...at least if u want to take it serious as an enduser distroat least competitive.
plus for me "swearing" doesn't mean the same as "insulting"  .... that's how the Finnish "language mentality" works... we use "swear" words to emphasis things (more or less) https://en.wikipedia.org/wiki/Finnish_profanity

--------------

*when leap 42.2 arrived I installed it and I found A LOT of problems with it and would never recommend it for "normal/enduser" desktop usage (nor tumbleweed)....at least if u are a nvidia user and/or a gamer and/or find video/audio stuff important...so thats like 90% of the user base...at least 70% (nvidia)....even Fedora had this same problems and now has come ahead and "fixed" these more or less...its not great solution but better than nothing.

I find it amusing that the closest thing for "best default out of the box experience" for normal/enduser desktop is coming from a arch based distro(s)....manjaro(-kde) ...yes there are some problems still but it seem to get way better every year...for me chakraOS is still my favorite distro ...which is also part of the arch family

YES...openSUSE has done some great things and there are some really nice things that I really appreciate...but like I said before there are some policy(/technical) decisions also that are just huge deal breakers ...which some I think are really out of date and some are just to try to please the FOSS extremist...if that is what openSUSE want ...Fine...but that will be a problem sooner or later...and at least if they want to attract normal end users.
so for now  openSUSE is same as centos/fedora is ...aka free/open development platform version of their enterprise counterpart.
is that good? well it's not a desktop distro at least...same goes with all the major ones...even ubuntu is more focused on server/enterprise than desktop..and they always will...so maybe thats why distros like manjaro are becoming better at that and gaining more popularity all the time.

--------

why am I using openSUSE then? well I broke my chakra installation (too much) after I tested some stuff out and then there is a problem with chakraOS and manjaro ISO latest ISO's and antergos ..at least for Nvidia gtx 970 users https://gitlab.chakralinux.org/tools/chakra-iso/issues/34

and openSUSE leap 42.2 was the latest thing available at the time...and as I liked openSUSE 13.x I thought I could give it a 2nd chance.

-----------------

anyway as this is really not the place to discuss either topic....(says the person who wrote buttload about it)
I wonder why I have this problem only with the "mpv build" and not with gstreamer/multimedia one? also I have other qt project that works just fine and they are also builded against leap 42.2's Qt5.6 and they work just fine on my Qt5.8 setup..

this seems to be some "wierd" obs/opensuse packaging problem

**Comment by rakslice** [comment]
I appreciate that these things are important to you, and I've tried to be constructive, but I don't understand what you this mean this as; if you have general issues with a distro you should find someone who cares and take your issues to them, not only because you're wasting people's time here, but because there is a universe in which it might actually result in the change you're looking for.

**Comment by ahjolinna** [comment]
@rakslice : I do agree, but unfortunately I can't avoid responding (at least when it comes stuff like this)....it's bad habit I know.

anyway in this case I'm still wondering why only the "mpv-build" has this qt problem and not qt-multimedia?...this could be some wierd obs/distro problem and not orion...so I will close this
