### ISSUE TITLE
[feature] remember the last VOD playback position

### ISSUE THREAD

**Issue by ahjolinna** [alamminsalo/orion#121]
there is few reason why I think this could be good..
1, if the stream is really long and want to watch it in sections.*
2, if the VOD playback stops for some reason or another (at least on qt-multimedia backend) and you press play again it wont return to the beginning.

(3)*when you open some VOD orion should ask that do you want to continue from the last position or start from beginning

**Comment by rakslice** [comment]
It would be cool to integrate with Twitch's own VOD position/save restore via the `resumewatching` API but there doesn't seem to be a publicly available OAuth scope that allows access to this yet.

**Comment by rakslice** [comment]
Re 2: I figured out what was going on with the multimedia backend https://github.com/alamminsalo/orion/pull/155

**Comment by ahjolinna** [comment]
@rakslice : it does fix the reload thing for qt-multimedia backend...but if the VOD playback stops (for some reason) it will still restart to the beginning...for some reason it happens way to often to me (on qt-multimedia backend only)

**Comment by CuddleBear92** [comment]
Close this issue cause its fixed?
