### ISSUE TITLE
small visual glitch with toggled chat/viewer list

### ISSUE THREAD

**Issue by ahjolinna** [alamminsalo/orion#128]
![image](https://cloud.githubusercontent.com/assets/6993072/25563797/4e40b486-2dac-11e7-86fe-b3849693c90e.png)

![image](https://cloud.githubusercontent.com/assets/6993072/25563805/6dd4f6ea-2dac-11e7-9f3a-41907e2f94a0.png)

this is on both vod and live streams

Is this intentional? I hope not as it looks wierd

**Comment by alamminsalo** [comment]
Yep it's a bug. Should've checked against non-black background, silly me

**Comment by alamminsalo** [comment]
fixed
