### ISSUE TITLE
Not all followed channels that are live appear live

### ISSUE THREAD

**Issue by kenga92** [alamminsalo/orion#13]
After playing around some more with this, I noticed that not all my followed channels that are live are actually displayed as such in the Favorites tab. 16 of the channels I followed are live, Orion for some reason only shows 10 of them as live. First suspected that it just fails to reload this list, as I had it open for quite a while - the issue occurs after a fresh start as well though. 
The channels do appear in the Favorites list, but are showed as offline, when this is clearly not the case. It also appears that these are always the same channels - after several restarts, always the same ones are wrongly displayed as offline. [Screenshot for comparison.](http://i.imgur.com/Tv9pYNb.jpg)
Are some channels handled differently by the Twitch API, as it is always specific channels failing to appear online?

**Comment by alamminsalo** [comment]
I suspect this could be a bug due to way channels are parsed from the streams return message. I'll take a look at this tomorrow, prob getting fixed soon

**Comment by alamminsalo** [comment]
I looked into this issue. It could be because Twitch API doesn't show channels broadcasting playlists as 'online', and that seems to be the case here (can't say for 100% sure, I need this to be confirmed by someone also running into this problem by checking if all these channels are running a playlist broadcast)

**Comment by kenga92** [comment]
Playlists as in re-running old broadcasts/VODs? If that is what you suspect, it's definitely not it - those were regular live broadcasts. It might've been the case for some of them, but the two I double-checked were definitely live, responding to chat on stream, etc.

**Comment by drgnak** [comment]
Can confirm that followed streams that are live aren't showing up as live, sometimes. Attached image shows following in Orion vs in Livestreamer Twitch GUI
![orion](https://cloud.githubusercontent.com/assets/2542868/18489201/3144dcc0-79c2-11e6-8737-7b0e55c78f9a.PNG)

**Comment by alamminsalo** [comment]
Fixed
