### ISSUE TITLE
Better Chat? edit: change chat size on Windows 10*

### ISSUE THREAD

**Issue by capitao3** [alamminsalo/orion#138]
First, I wanna say this program is amazing. I've been looking for this for a very long time, it is stable and way better and easier to use than streamlink/livestreamer.

Thank you very much for it.

I only request better chat options and configuration, like allowing to make it bigger, BTTV or FFZ emotes, whispers etc.

This would be perfect.
Again, thank you.

**Comment by ahjolinna** [comment]
@capitao3 : [whisper feature](https://github.com/alamminsalo/orion/issues/108) was just implemented, what do u mean by bigger? (how much) also is the text size good enough? if not maybe there is a problem with the (hi)dpi feature, but if that is the problem maybe this [new commit ](https://github.com/alamminsalo/orion/pull/133)will fix it

**Comment by capitao3** [comment]
Allow to drag and make chat bigger, with bigger letters and emotes, shrinking the stream, optionally.
I use Orion like this: http://i.imgur.com/66sUSPS.jpg.
Instead of the normal way: http://i.imgur.com/vHrWu47.jpg.

It's actually because my sight sucks (even with glasses), it's not an issue of the program itself.

It would just help few people with pleb sight (me).

![66susps](https://cloud.githubusercontent.com/assets/28553782/25857211/c26db40e-34ae-11e7-86b5-80bb73d46eb1.jpg)
![vhrwu47](https://cloud.githubusercontent.com/assets/28553782/25857210/c26b4f34-34ae-11e7-9ce2-7cd97906a865.jpg)

**Comment by ahjolinna** [comment]
as it seems you are on win10 and @rakslice is more the windows user/dev "here" I would "throw" this issue to him

**Comment by capitao3** [comment]
Yes, I'm.

Thanks for replying, going to msg him.

**Comment by rakslice** [comment]
@capitao3 FYI, as a possible workaround, depending on the DPI that Qt detects for your monitor, setting the environment variable `QT_AUTO_SCREEN_SCALE_FACTOR` to `1` (Win+Break -> Advanced System Settings -> Advanced tab -> Environment Variables) may give you larger images and text for things that use pixel-sized fonts. See https://doc.qt.io/qt-5/highdpi.html#high-dpi-support-in-qt for more info on this.

Anyway, IMO there really should be a setting in Orion that adjusts font size, both for visibility issues and as a workaround when Qt a DPI value that doesn't correspond to reality.
I'm thinking that a size dropdown on the settings screen with named presets would be best.  This could just apply a factor to the `dp()` calculation, as widgets that contain text would need to be scaled along with the text.  IMO if the chat area is made drag-resizeable people are going to resize it expecting it to show more chat, not larger chat.

**Comment by rakslice** [comment]
Another workaround is to just scale _everything_ by setting `QT_SCALE_FACTOR` to whatever magnification factor makes sense for you.

**Comment by ahjolinna** [comment]
@rakslice : well maybe orion should have in settings to set some (pre-made) font sizes and/or force font DPI levels...kde/plasma5 has done it like this:
![image](https://cloud.githubusercontent.com/assets/6993072/25872885/f964426e-3514-11e7-96c4-026fc849c5ea.png)

amongst screen scaling setting:
![image](https://cloud.githubusercontent.com/assets/6993072/25872842/d317aede-3514-11e7-8661-f24a82d3ddef.png)

**Comment by rakslice** [comment]
I added separate issues for the emote feature requests https://github.com/alamminsalo/orion/issues/140 https://github.com/alamminsalo/orion/issues/141

**Comment by ahjolinna** [comment]
@rakslice : damn it seems those emote's are png based, why can't they be svg ...sigh...anyway... if there are any common sizes between those two (BetterTwitchTV and FrankerFaceZ emotes) why not make them as optional value in settings...just a dropdown menu that has a preview of those different sizes

**Comment by capitao3** [comment]
@rakslice, I used QT_SCALE_FACTOR and the value 2,  it's like this now: http://i.imgur.com/fCqPcpb.png

![fcqpcpb](https://cloud.githubusercontent.com/assets/28553782/25878675/dd30b6a2-3502-11e7-93a7-a4436115ce85.png)

It worked, I'm impressed. The program is 100% fine for me now.

Thank you very much for the help @ahjolinna and @rakslice.
