### ISSUE TITLE
Package correction

### ISSUE THREAD

**Issue by bharadwaj-raju** [alamminsalo/orion#14]
> `sudo pacman -S git gcc qtcreator qt5-svg qt5-webengine qtav`

Qt Creator is not needed. `qmake` will be sufficient.

**Comment by alamminsalo** [comment]
Thanks for pointing this out. Fixed

**Comment by lolzballs** [comment]
[`qmake` isn't a package](https://www.archlinux.org/packages/?sort=&q=qmake&maintainer=&flagged=).  As well, `qt5-quickcontrols` is required for orion to run.

**Comment by alamminsalo** [comment]
Replaced qmake by qt5-base and qt5-quickcontrols

**Comment by bharadwaj-raju** [comment]
Oh, OK. Close?
