### ISSUE TITLE
bigger cache for VOD's?

### ISSUE THREAD

**Issue by ahjolinna** [alamminsalo/orion#143]
I'm not sure how big the cache is for VOD's or in general...anyway as at least with gst-backend has problem resuming the playback if the connection is to slow (on your end or twitch), its really annoying when the stream just stops and pressing play/reload will start the VOD from begging and when some stream are hours long this is really pain...I also notice that orion starts to skip few seconds at times I think this is related to the download/cache problem also

currently I "have" to use 4G connection instead of fiber (long story why), anyway this is my speed:
![image](https://cloud.githubusercontent.com/assets/6993072/25883979/ae8fde04-3557-11e7-82b7-6fee75aeb819.png)
and still I get slowdowns at times ...I think its mostly twitch problem as sometimes I don't have any problems and this is way more noticeable on orion compare to web or android app

also I think it would be good to start the playback when your cache is filled up with x kB so there would be some buffer data

for mpv there is something like this: https://github.com/lvml/mpv-plugin-streamcache

maybe that or something a like could be added to mpv or in general (for all backends)

**Comment by rakslice** [comment]
Would it be possible to make seeking work with all the backends? It works already when using libmpv.

**Comment by ahjolinna** [comment]
@rakslice : well seeking does work on gst but I dont know about qtav...
and about mpv...I should really test mpv again as there has been a HSL bug in ffmpeg/mpv for a longtime that made streaming unplayable... I should check if its relevant...but oc I cant get it to build on obs/openSUSE...sigh...so I have to test it on chakraOS..

anyway this bigger cache/buffer thing could be good also for live streams not just VOD's

**Comment by ahjolinna** [comment]
it seems the ffmpeg/mpv's  HLS stream bug have been resolved after years of waiting...sigh.. as it seems to work fine on my ultrabook/manjaro-kde

**Comment by ahjolinna** [comment]
anyway it seems finally MPV is usable on linux and works way better than gstreamer...I have been waiting for this...anyway I really dont care for gst anymore so I will close this.. but I need to try to get mpv version to build on obs...hmm

I will make a new bug report about some changes I want for mpv
