### ISSUE TITLE
"stream name problem" with mpv-backend on pulseaudio?

### ISSUE THREAD

**Issue by ahjolinna** [alamminsalo/orion#150]
I just now notice when testing "mpv-build" on manjaro-kde that the naming for orion in (kde) audio applet is wrong, seems to be a pulseadio "problem" aka pulse metadata support: 
![image](https://cloud.githubusercontent.com/assets/6993072/26022355/e5256d52-37ab-11e7-96b1-4c6854348e1e.png)

this is how it looks with qt5-multimedia backend:
![image](https://cloud.githubusercontent.com/assets/6993072/26022374/d2d434ac-37ac-11e7-9a92-d8089cc72e6c.png)
.....which is better..
but I think it would be better to have "orion: (streamername)" ...at least if we will add https://github.com/alamminsalo/orion/issues/89
...[mpc-qt](https://github.com/cmdrkotori/mpc-qt) has done something like this and its qt5 project that use mpv

check pulseaudio documentation : https://github.com/alamminsalo/orion/issues/89

**Comment by rakslice** [comment]
Coincidentally I also noticed these `index-*.m3u8` stream names getting into pulseaudio from mpv-based builds when I went into `pavucontrol` to fiddle with channel balances to pan individual orion sessions. Actually, at first I used the stock `pavucontrol` version in debian jessie which showed several hundred character alphanumeric IDs for each stream, and this actually made it impossible to shrink the window smaller than about 3 screens wide. When I switched to a build of https://github.com/pulseaudio/pavucontrol master (with an intent to look into the layout bug) the ids were replaced with these stream names.

The Windows mixer also sees these `index-*.m3u8` stream names from mpv-based builds.

From the mpv docs it looks like this can be overridden with the `audio-client-name` option, although I haven't verified that.

**Comment by rakslice** [comment]
also `title` option https://mpv.io/manual/master/#options-title

**Comment by rakslice** [comment]
Doesn't seem like `MediaPlayer` provides any way to override metadata, so we are stuck with "Playback Stream" for a title there

**Comment by ahjolinna** [comment]
@rakslice : thanks for the fast "fix", I can/will now check it out when obs is finally online. Anyway like I said before; it would be nice to change that "Playback Stream" to the current stream's channel name you are watching, this would be good at least when ["multistream support"](https://github.com/alamminsalo/orion/issues/89) arrives someday

**Comment by rakslice** [comment]
Created an upstream bug with hope to get some ability to emit metadata when using MediaPlayer https://bugreports.qt.io/browse/QTBUG-60840

**Comment by ahjolinna** [comment]
@rakslice : okay qt-multimedia is upstream problem, what about MPV -backend? ...at least mpc-qt has done this (with "local" files)

**Comment by ahjolinna** [comment]
anyway I will close this issue now as the orginal mpv issue has been fixed and the qt-multimedia is a upstream issue...maybe there is some workaround?
