### ISSUE TITLE
Followed Channels list is empty.

### ISSUE THREAD

**Issue by legacynl** [alamminsalo/orion#151]
Since i updated to 1.5.1 Orion doesn't correctly save/load my followed channels.

I can correctly follow and unfollow channels, however when I exit and open Orion the list is empty again.

The contents of /home/username/.config/orion.application/Orion.conf are:
`[General]
access_token=
alert=true
alertPosition=1
closeToTray=false
minimizeOnStartup=false
notifications=false
swapChat=false
textScaleFactor=0.75
volumeLevel=30

[channels]
1\alert=true
1\id=151123442
1\info=
1\logouri=https://static-cdn.jtvnw.net/jtv_user_pictures/subaruesports-profile_image-055c2597842cc6aa-300x300.jpeg
1\name=SubaruEsports
1\previewuri=https://static-cdn.jtvnw.net/previews-ttv/live_user_subaruesports-640x360.jpg
1\serviceName=subaruesports
1\timestamp=1494703399747
2\alert=true
2\id=20702886
2\info=Blind Kaizo Race! Very Short Stream While Experiment Runs
2\logouri=https://static-cdn.jtvnw.net/jtv_user_pictures/carlsagan42-profile_image-4f9713e92e4b1149-300x300.png
2\name=Carlsagan42
2\previewuri=
2\serviceName=carlsagan42
2\timestamp=0
3\alert=true
3\id=56865374
3\info="Making dumb level for GoSeigen, then 1k viewer levels"
3\logouri=https://static-cdn.jtvnw.net/jtv_user_pictures/barbarousking-profile_image-e76c206d0615cec3-300x300.png
3\name=BarbarousKing
3\previewuri=https://static-cdn.jtvnw.net/previews-ttv/live_user_barbarousking-640x360.jpg
3\serviceName=barbarousking
3\timestamp=1494701934142
4\alert=true
4\id=22025290
4\info=S A L T Y Yu-Gi-Oh \x25a4 FREE SHADOW REALM VACATIONS!
4\logouri=https://static-cdn.jtvnw.net/jtv_user_pictures/trihex-profile_image-3500a1fa02941578-300x300.jpeg
4\name=trihex
4\previewuri=
4\serviceName=trihex
4\timestamp=0
size=0
`

**Comment by legacynl** [comment]
Looking at the load() and save() code, I can't really figure out what's the problem. The save() function clearly works, and load() looks like it does the same in reverse (although my experience with qt is limited). 

Is there anyway to see debug output?

**Comment by rakslice** [comment]
I didn't even know that local favourites was a feature.

Looks like in `ChannelManager::load()` it is checking `settings.contains("channels")` but it seems even when there is a readable channels array that never becomes true (maybe because there is no **key** called channels?)

Also, immediately after I launched a version with that change in a debugger and logged out of Twitch on the settings view and switched back to the followed view it did an API query for my online followed list (!?) and put that in the local favourites model.. :/

**Comment by rakslice** [comment]
@legacynl For debug output you can comment out the null message handler setup at main.cpp:70 although I don't know that any of the debug output that would be useful for this problem.
