### ISSUE TITLE
livestreamer for MPV?

### ISSUE THREAD

**Issue by ahjolinna** [alamminsalo/orion#16]
watching any video streams on MPV doesn't work that well, I can't remember the reason  why the buffering wont work (it's a known problem in MPV/ffmpeg), but if you are using MPV with livestreamer then it will work just fine.

the command for it to work with mpv is: 
`livestreamer -p mpv <url> <quality> --player-continuous-http`
example:
`livestreamer -p mpv https://www.twitch.tv/angryjoeshow best --player-continuous-http`

with orion or mpv in general I can't watch the source quality at all but with livestreamer it does work just fine (in web browser or/and my phone), I have a 150M connection so it should be enough

**Comment by ahjolinna** [comment]
I just remember that sailfishOS own[ twitch client ](https://github.com/Aldrog/TwitchTube)(qt5 based) uses qt5-multimedia and that seems to work just fine, I don't think qtav is needed at all..so either or

**Comment by alamminsalo** [comment]
I need to investigate on this, though I can recall at start I tried to use qt5-multimedia. Can't remember anymore what was the issue I had with it, ending up using mpv instead

**Comment by alamminsalo** [comment]
From quick testing on mac and linux, I could be able to make a compile flag which uses qt5-multimedia. QtAV uses identically named and interfaced qml-objects, so it's pretty easy to swap them. Then only thing left for you would be to install qt5-multimedia package and enable that compile flag

**Comment by ahjolinna** [comment]
I know that the old/previous qt5 versions had "few" problems here and there on linux/KDE, I mean at least before 5.6.1 (LTS)...v5.7 is way better, and as an KDE/plasma5 user I cant wait for Qt5.8 (and plasma 5.8, the LTS release)

I don't know what is the minimum qt5 requirement for orion, but I would think Qt5.6.1 would be a good standard as it's a LTS version

PS. I notice that this happens when I try to open a stream :[ log output](https://paste.kde.org/pfeyilflz)

PPS. I'm running [chakraOS](https://chakralinux.org/), and using aur/pkgbuild (git version)

**Comment by alamminsalo** [comment]
I can see from the log that the stream is choppy / buffering a lot for you. You can try using qtmultimedia right now by:

- Adding `QT += multimedia` to .pro
- Commenting out `QT += av` and `CONFIG += mpv` lines from .pro
- Replacing `import QtAV 1.7` by `import QtMultimedia 5.6` in GstPlayer.qml (for multimedia, import the highest version you have)

If you do, tell me how it went and if it did fix your buffering issues. Note that using qtmultimedia requires gstreamer for linux IIRC

**Comment by ahjolinna** [comment]
seems to work, there was some "visual glitching" on the first seconds but then it was just fine

**Comment by ahjolinna** [comment]
mä suljen tän nyt, tee mitä teet tämän "infon" kanssa :D 
se hieno että sä teit Qt/qml ohjelman ja etkä minkään köyhän miehen "webapp" (electron), ainiin jos sua kiinostaa tehdä jotain muuta kuin tää niin Discord Qt/qml versio olis kiva linux:lle koska se virallinen on joku kuppanen webapp -_- ...joku on jo aloittanut sellaisen : [QDiscord](https://github.com/george99g/QDiscord)

(PS. ehkä libnotify tuki vois laitaa?)
