### ISSUE TITLE
Strange UI Issue

### ISSUE THREAD

**Issue by XenonPK** [alamminsalo/orion#163]
![screenshot_20170525_092037](https://cloud.githubusercontent.com/assets/8293194/26442245/92b2d2e2-412b-11e7-9c5a-a28e44e18c43.png)

Has anyone encountered this? All the icons that make up the UI suddenly stopped loading, even after completely removing any trace of Orion from the system and installing the package again.

**Comment by rakslice** [comment]
I haven't had this happen to me. Does this only affect `fontawesome` icons? They should be displaying using the fonts/fontawesome-webfont.ttf included as a resource...

**Comment by ahjolinna** [comment]
I have this problem longtime ago on other apps, at least on firefox once....I think it was fontconfig issue or something absurd like that

maybe try to clear "~/.cache/fontconfig/" ??

**Comment by XenonPK** [comment]
Clearing the font cache and installing fontawesome-fonts fixed the issue, thanks @rakslice and @ahjolinna , I'll add this as a dependency.

**Comment by rakslice** [comment]
If an external fontawesome font is required, then something else is wrong with the bundled font resource... What distro is that on so I can attempt to reproduce?

**Comment by XenonPK** [comment]
OpenSUSE Tumbleweed, however, i find it unlikely you'll be able to reproduce it easily, as in my desktop machine this does not happen at all, even without the additional fontconfig dependency.
The package is in the official repos.
