### ISSUE TITLE
Disable Screensaver Not Working

### ISSUE THREAD

**Issue by ahjolinna** [alamminsalo/orion#164]
it would be nice to have (extended) option to choose between different option's to disable screensaver when orion is in fullscreen and/or video is playing

apprently gnome uses their own thing and kde uses freedesktop standards.. (ironically)..I think, I would check how bomi-player has done it:
![image](https://cloud.githubusercontent.com/assets/6993072/26523125/3cb41ba4-4319-11e7-9290-e210bbc7d459.png)

....:
"org.gnome.SessionManager.Inhibit
"org.freedesktop.screenSaver.Inhibit"
&
"XScreenSaver

**Comment by rakslice** [comment]
Would it be a problem if the screensaver was disabled through all of the available supported APIs all the time?

**Comment by ahjolinna** [comment]
well in bomi's case, that's what the auto is, it will use that API what is currently in use...and if it can't recognize or chooses the wrong one you have the option to choose manually the correct one

I think the API thing should be just "auto" with only option to choose with; "in fullscreen only and/or while video is playing" ...
