### ISSUE TITLE
possibility to restart the stream

### ISSUE THREAD

**Issue by ahjolinna** [alamminsalo/orion#17]
if the streamer has some problems like the stream crashes and/or the stream has be to restarted, it would be nice if you had the possiblity to restart the video playback manually if it wont automatically reconnect...and without "loosing" the chat (log) by reconnecting/refreshing it also.

Switching between pause/play doesn't work, the apps still thinks the stream is offline (and chat works just fine)

**Comment by alamminsalo** [comment]
On the 'dev'-branch, there is now experimental feature which attempts to load stream back if it goes offline. Also chat log only clears now when changing channels. Also added BACKEND_MULTIMEDIA config-switch for using qt's own multimedia backend

**Comment by ahjolinna** [comment]
okay, kiitos I will test it tommorrow

**Comment by ahjolinna** [comment]
okay it seems I don't have a life...again..anyway..

about your "BACKEND_MULTIMEDIA config-switch" ...ööö...so it seems if you have all 3 of backends installed it will use MPV by default...it's not a problem for me, I just made a small workaround for [my pkgbuild](https://chakralinux.org/ccr/pkgbuild_view.php?p=orion-git) that will make the qt5-multimedia default. (I oc have an other version that I adjusted for the dev branch)

it would be nice when compiling if there was some configure flag to specify the default backend, or have an option in settings to choose between your available backends

why I have all 3?...well...I use MPV as my default video player for my local videos after the [bomi project](http://bomi-player.github.io/) died (well almost)...qtav, I don't remember why I have it anymore...I have like 130 ccr pkgs to maintain (chakraOS own AUR)

**Comment by ahjolinna** [comment]
...oh and chat..sigh how should I explain this, it seems when you exit from fullscreen the chat won't do readjusting, so you have to move the conversation manually so it will continue

wtf..now when I was writing the favorite section and video playback doesn't work (api problem?) ...chat did work
[error output log](https://paste.kde.org/pu9grzgjj/tfje2u/raw)

**Comment by alamminsalo** [comment]
About your last issue: Twitch apparently changed their api so that all request made need to have client id included. I fixed this in both master and dev branches.

**Comment by ahjolinna** [comment]
why is the  `CONFIG *= mpv` instead of `CONFIG += mpv` ? (line 57, orion.pro)...typo?

**Comment by alamminsalo** [comment]
Because *= adds only if it's not already added (eg. user specified it manually)

**Comment by ahjolinna** [comment]
okay, fine..I'm more used to the [configure flag](https://www.gnu.org/prep/standards/html_node/Configuration.html) option than editing the source for stuff like this. 

anyway there hasn't been any of those stream crash problems yet, so I can't say how your fix works, but I will when that times comes (it happens quite often)

**Comment by alamminsalo** [comment]
Okay, if this seems to solve the issue, you can close this then

**Comment by ahjolinna** [comment]
I just notice that when you have muted the audio for a while and when you unmute it the video stops playing, pressing the play button doesn't help. There wasn't any errors in gdb.

maybe V/A is out of sync and that's why it "crashed/closed"?

**Comment by ahjolinna** [comment]
it doesn't seem to work, maybe restart button could be added?

also the chat doesn't seem to work correctly, it just stops on place and you have to scroll it so it will move/update normaly again

**Comment by alamminsalo** [comment]
Chat issue fixed

**Comment by alamminsalo** [comment]
I haven't added a restart-button yet, but the by toggling stream quality, it should do pretty much the same thing as restarting (well, not as convenient but suits for now...)

**Comment by ahjolinna** [comment]
well, this was done in 1.3.5 so I will close this
