### ISSUE TITLE
Followed channels list truncated

### ISSUE THREAD

**Issue by ROBOKiTTY** [alamminsalo/orion#179]
1.5.1-rc Windows

Showing 24 channels, but I follow 73 channels on Twitch.

**Comment by ahjolinna** [comment]
@ROBOKiTTY : this has already been fixed : #165 
it will be in the next release

**Comment by ahjolinna** [comment]
This issue can be closed as 1.6 is out and should have this resolved 

_Sent from my Sony F5121 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_
