### ISSUE TITLE
1.6.0: streams keep being stopped

### ISSUE THREAD

**Issue by WyohKnott** [alamminsalo/orion#189]
Since 1.6.0beta, streams keep being stopped after a few min of use and do not reconnect automatically. It seems that before, the reconnect was automatic.

(also you should add the minimum version of Qt on the README page for the material-ui version)

**Comment by WyohKnott** [comment]
I downgraded to version 1.4 and it was still happening, so I don't think it's an issue with new code.
It only happens in some streams and not others. When I pause the stream for a few seconds then it doesn't happen, so I think it's a problem that could be resolved by increasing the buffer of the streams.

**Comment by ahjolinna** [comment]
@WyohKnott : what platfrom are you testing on? (win7,8,10 or linux* or mac)... also do you have any examples with what channels/streams this keeps happening on? (also are their VOD's affected)

also have you tried with the lower quality settings, not just the Source quality as it can require A LOT of bandwidth


-----

*if linux, what backend?

**Comment by WyohKnott** [comment]
Linux Fedora 26 with Qt multimedia backend.

Streamer: Drupal, Fremily, Dexbonus

VOD is fine. 

_Sent from my LGE LG-H815 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by ahjolinna** [comment]
I will test them out soon, anyway.. 

Do you have all gstreamer codecs installed?

Also for me at least the MPV backend has  now been working perfectly, compared to the Qt-multimedia version which has been little bit of a hit and miss (depending on the distros at least) 

_Sent from my Sony F5121 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by ahjolinna** [comment]
I just tested Fremily stream...I think/hope... as they seem to be online now, and it works for me just fine...okay I'm using MPV backend and I have a basic 100M connection:

my system spec (yours?): 

```
[ahjolinna@arch-anywhere]: ~>$ inxi -b
System:    Host: arch-anywhere Kernel: 4.11.9-1-ck-skylake x86_64 (64 bit) Desktop: KDE Plasma 5.10.3
           Distro: Arch Linux
Machine:   Device: desktop Mobo: ASUSTeK model: Z170 PRO GAMING v: Rev X.0x UEFI: American Megatrends v: 2003 date: 09/19/2016
CPU:       Quad core Intel Core i5-6600K (-MCP-) speed/max: 4144/4400 MHz
Graphics:  Card: NVIDIA GM204 [GeForce GTX 970]
           Display Server: x11 (X.Org 1.19.3) driver: nvidia Resolution: 1920x1080@60.00hz, 1920x1080@60.00hz
           OpenGL: renderer: GeForce GTX 970/PCIe/SSE2 version: 4.5.0 NVIDIA 381.22
Network:   Card: Intel Ethernet Connection (2) I219-V driver: e1000e
Drives:    HDD Total Size: 12114.3GB (93.6% used)
Info:      Processes: 300 Uptime: 4 days Memory: 6643.8/15966.9MB Client: Shell (bash) inxi: 2.3.23 
```

**Comment by ahjolinna** [comment]
@WyohKnott : did you have this same buffering problem when watching from the twitch website, if you have then its your connection if not ... the only problem with bigger cache is that the "stream delay" will increase.

At least in mpv the "cache-initial=" settings needs to be added/or higher value so it will start playback when your cache is filled up with x kB, or something like [this plugin/script](https://github.com/lvml/mpv-plugin-streamcache) (mpv only) @alamminsalo @rakslice your thoughts?

**Comment by ahjolinna** [comment]
@WyohKnott : also did you run/debug the orion with gdb? (with that debug parameter)

**Comment by WyohKnott** [comment]
@ahjolinna I don't have any problems with the website or the android app even while I'm downloading torrents, so its not my connection.   
I don't know how to use gdb, I'll look it up. 

_Sent from my LGE LG-H815 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by ahjolinna** [comment]
Well in short install gdb... 
The run these commands :

gdb orion (or the executables location)

run - d

And when it crashes : bt full

_Sent from my Sony F5121 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by WyohKnott** [comment]
Closing as it doesn't to happen anymore with 1.6.1.
