### ISSUE TITLE
[question] Orion/Qt Licensing

### ISSUE THREAD

**Issue by ahjolinna** [alamminsalo/orion#191]
I'm little bit confused as which license orion should be using, as Orion currently is using  basic GPL v3 and it seem the opensource Qt projects should be using LGPL v3? ....thought some stuff do u use other : http://doc.qt.io/qt-5/licenses-used-in-qt.html 

source: http://doc.qt.io/qt-5/licensing.html
and 
https://www.qt.io/licensing/
and 
https://www.qt.io/faq/#_Toc_3
and
http://doc.qt.io/qt-5/opensourcelicense.html

**Comment by alamminsalo** [comment]
There's no clash. LGPL3 is compatible to be used in GPL3 licensed source

**Comment by ahjolinna** [comment]
as long as there is no clash then its fine, my confusion was more to do with that what license does Qt5 require for the opensource devs  to use with their created software. it seems KDE uses GPLv2, which I personally prefer over v3 ...LGPLv 2.1 is also fine (what for example [MPV uses now](https://github.com/mpv-player/mpv/issues/2033))...

I never liked the newer "basic" GPLv3, mostly for the same [reasons as Linus T.](https://www.youtube.com/watch?v=PaKIZ7gJlRU) but if v3 is the license you like for Orion, I think I will survive :D

**Comment by rakslice** [comment]
@ahjolinna 
LGPLv3 only requires you to provide the application code in a form suitable for relinking, which could be just object code and not source, with a license that allows relinking. https://www.gnu.org/licenses/lgpl-3.0.en.html#section4. This is what the Qt licensing docs presumably mean when they say "provided you can comply with the terms and conditions of the GNU LGPL version 3".
