### ISSUE TITLE
Make a final release for version 1.5.1

### ISSUE THREAD

**Issue by WyohKnott** [alamminsalo/orion#197]
Hello,

Could you make a last release for the version before the introduction of the material design? I don't know the commit number, I think it's commit 253729a23ac1fea6dc75bd67273f6735383899bf . Not many distribution have the qt-quickcontrol2 5.8 yet and it would help to have a reference point for packaging.

Thanks.

**Comment by ahjolinna** [comment]
I do agree that Orion should have tried to stay with Qt5.6 (LTS) as long as possible...but then again it seems to be hard, even KDE had to move to Qt5.7 as a minimum version.

now only way for those "older" distros to use Orion would be using a snap/flatpak/appimage pkgs ...

but at least Qt5.9 seems to be a better LTS release compare to 5.6 that was more of "we need a LTS version now" thing...

-----------

Side note:

I personally do think that this "old" release model what many desktop distros still use is ...well..old...
more distros should update towards a rolling or [half/semi-rolling model](https://en.wikipedia.org/wiki/Rolling_distribution#Part-rolling.2C_semi-rolling.2C_or_half-rolling_distributions)

I have been using arch (-kde) and chakraOS for years now and they haven't broken yet...some small problems at times, I have had way more problems with these "old distros"

**Comment by alamminsalo** [comment]
https://github.com/alamminsalo/orion/releases/tag/v1.5.1

**Comment by probonopd** [comment]
Providing an [AppImage](http://appimage.org/) would have, among others, these advantages:
- Applications packaged as an AppImage can run on many distributions (including Ubuntu, Fedora, openSUSE, CentOS, elementaryOS, Linux Mint, and others)
- One app = one file = super simple for users: just download one AppImage file, [make it executable](http://discourse.appimage.org/t/how-to-make-an-appimage-executable/80), and run
- No unpacking or installation necessary
- No root needed
- No system libraries changed
- Works out of the box, no installation of runtimes needed
- Optional desktop integration with `appimaged`
- Optional binary delta updates, e.g., for continuous builds (only download the binary diff) using AppImageUpdate
- Can optionally GPG2-sign your AppImages (inside the file)
- Works on Live ISOs
- Can use the same AppImages when dual-booting multiple distributions

[Here is an overview](https://github.com/probonopd/AppImageKit/wiki/AppImages) of projects that are already distributing upstream-provided, official AppImages.

**Comment by WyohKnott** [comment]
Thank you! 

_Sent from my Google Nexus 7 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_
