### ISSUE TITLE
Problem in ArchLinux

### ISSUE THREAD

**Issue by Masseus** [alamminsalo/orion#198]
Hello,
i follow all the steps to install in my arch setup. But whenever i start the app in the terminal say this:
Selected default network configuration
 "[1]    4787 segmentation fault (core dumped)  orion"

**Comment by ahjolinna** [comment]
have you tried to rebuild orion? and could you try to run orion in gdb with the debugging command line option : -d / -debug

-------------

```
gdb orion
run - d

And when it crashes : bt full
```

**Comment by Kalagon** [comment]
I have the same issue. Happens on multiple machines, both `orion` and `orion-git` are affected. Everything's up-to-date. The requested debug info can be found here https://pastebin.com/h8C0E0ux

**Comment by ahjolinna** [comment]
It seems this could be related to issue #192, you apparently need to install qt5-graphicaleffects 

_Sent from my Sony F5121 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by Kalagon** [comment]
Sadly that does not fix it. I installed `qt5-graphicaleffects`, rebuilt both `orion` and `qt5-styleplugins`, rebooted. The same issue still appears. :/

**Comment by Masseus** [comment]
`System:    Host: fran-x230 Kernel: 4.11.9-1-ARCH x86_64 (64 bit) Desktop: Xfce 4.12.4 Distro: Arch Linux
Machine:   Device: laptop System: LENOVO product: 23254UY v: ThinkPad X230
           Mobo: LENOVO model: 23254UY UEFI [Legacy]: LENOVO v: G2ET32WW (1.12 ) date: 05/30/2012
Battery    BAT0: charge: 30.8 Wh 89.6% condition: 34.4/62.2 Wh (55%)
CPU:       Dual core Intel Core i5-3320M (-HT-MCP-) speed/max: 2245/3300 MHz
Graphics:  Card: Intel 3rd Gen Core processor Graphics Controller
           Display Server: N/A driver: N/A tty size: 150x40
Network:   Card-1: Intel 82579LM Gigabit Network Connection driver: e1000e
           Card-2: Intel Centrino Advanced-N 6205 [Taylor Peak] driver: iwlwifi
Drives:    HDD Total Size: 440.1GB (16.3% used)
Info:      Processes: 174 Uptime: 29 min Memory: 2014.5/3676.1MB Init: systemd Client: Shell (zsh) inxi: 2.3.23 `
There is the inxi -b.

I rebuild the package from yaourt, orion-git.
And now say this 
[1]    6469 segmentation fault (core dumped)  orion

I install the qt5-graphicaleffects before rebuild all, but the app its not opening.

**Comment by ahjolinna** [comment]
well this runs just fine on my arch -stable (KDE), only difference from the AUR version is that I use MPV backend instead of the Qt-multimedia (/gstreamer), I also installed the qt5-styleplugins and still worked just fine with it

@Masseus @Kalagon : if you are using qt-multimedia backend could you try the mpv one, and also do new gdb run ...also a strace output could help:

```
strace -eopen orion
or/and
strace -o /dev/stdout orion | grep string
```

-------
```
inxi -b
System:    Host: arch-anywhere Kernel: 4.11.11-1-ck-skylake x86_64 (64 bit) Desktop: KDE Plasma 5.10.4
           Distro: Arch Linux
Machine:   Device: desktop Mobo: ASUSTeK model: Z170 PRO GAMING v: Rev X.0x UEFI: American Megatrends v: 2003 date: 09/19/2016
CPU:       Quad core Intel Core i5-6600K (-MCP-) speed/max: 4365/4400 MHz
Graphics:  Card: NVIDIA GM204 [GeForce GTX 970]
           Display Server: x11 (X.Org 1.19.3) driver: nvidia Resolution: 1920x1080@60.00hz, 1920x1080@60.00hz
           OpenGL: renderer: GeForce GTX 970/PCIe/SSE2 version: 4.5.0 NVIDIA 381.22
Network:   Card: Intel Ethernet Connection (2) I219-V driver: e1000e
Drives:    HDD Total Size: 12114.3GB (94.6% used)
Info:      Processes: 353 Uptime: 4 days Memory: 7624.0/15966.9MB Client: Shell (bash) inxi: 2.3.23
```

**Comment by Kalagon** [comment]
I used the default PKGBUILD which uses mpv, so that does not seem to be the issue.
Nevertheless I found the issue, which I could've seen sooner. The package is missing the `qt5-quickcontrols` dependency. I'll post this in the aur so the package should be changed.

**Comment by alamminsalo** [comment]
Please close the issue if resolved

**Comment by ahjolinna** [comment]
@alamminsalo : Orion still needs both v1 and v2 of quickcontrols? I thought this new material design removed the need of v1

**Comment by Masseus** [comment]
So, today i open orion and its opening.

I dont know what are, but well .I close the issue 

Thanks
