### ISSUE TITLE
player is all black

### ISSUE THREAD

**Issue by icf20** [alamminsalo/orion#218]
none of the stream/vod actually play there is just a black screen

player mpv
dist opensuse tumble weed

**Comment by ahjolinna** [comment]
what repo do use to get orion? Also can you give the [GDB output](https://wiki.archlinux.org/index.php/Step-by-step_debugging_guide#Gdb)

**Comment by icf20** [comment]
@ahjolinna  this one https://build.opensuse.org/package/show/openSUSE%3AFactory/orion

**Comment by ahjolinna** [comment]
well that one is builded against openSUSE factory which is little bit different from tumbleweed, try this one as this has the tumbleweed version: https://build.opensuse.org/package/show/games:tools/orion

if that doesn't work either, then plz give your gdb output for debugging

as everything works for me on arch linux, and I'm even using using Qt5.10-beta4 +mpv(-full)-git (and ffmpeg-mpv-full-git)
