### ISSUE TITLE
High cpu usage compared to v1.6.1

### ISSUE THREAD

**Issue by abstrakct** [alamminsalo/orion#230]
Hello, I recently upgraded from 1.6.1 to the current git version - https://github.com/alamminsalo/orion/commit/ce0ac00e830629ef2dde0634f6cdff2d0e1a3842 - and saw that orion is now using a lot more cpu than before. On my computer (which is old and crappy) 1.6.1 uses 7-10 % cpu when playing a stream or a vod, which is absolutely beautiful, compared to watching twitch in a browser which uses 50-80 % cpu! But chat playback in vods didn't work in 1.6.1 so I upgraded. Now chat playback works, but orion uses 40-50 % cpu! Still better than the browser, but a significant downgrade performance-wise. On an old computer like mine, it does have an impact if I want to play a stream/vod while doing something else that is also cpu intensive.
Any idea why this is happening or what introduced this, and could it be fixed? 
I've tried switching back and forth between 1.6.1 and current git version, and the results are consistent.
I'm running Arch Linux, cpu is AMD Phenom II X4 965 3.7 GHz, gpu is an old GTX 560.

**Comment by ahjolinna** [comment]
the orion-git pkgs version uses qt-multimedia as backend, have you tried switching to mpv? which works for way better at least for me (1-2 % cpu usage). I also use mpv-full and ffmpeg-full from aur (they are not required but nice to have).

PS. also check that you have libvdpau (obsolete) installed for hardware acceleration, or soon cuda for cuvid (when ffmpeg 3.5 arrives)

**Comment by ahjolinna** [comment]
the[ basic/stable orion](https://aur.archlinux.org/packages/orion/) seem to use mpv by default, and it has the latest changes so you can use it

**Comment by ahjolinna** [comment]
@abstrakct : anything?

**Comment by abstrakct** [comment]
Hi, thanks for your reply and sorry for replying so late! I wasn't aware that orion has different backends to choose from, and never looked at the pkgbuild. I saw your replies now and changed the backend to mpv in the pkgbuild, as suggested, and that has absolutely fixed the problem! CPU usage is back to a nice low percentage :)
Thanks again!
