### ISSUE TITLE
Orion 1.6.5 x64 not starting on Windows

### ISSUE THREAD

**Issue by fehrm** [alamminsalo/orion#231]
Hello, 
I can't get 1.6.5 x64 Orion to start on Windows 10. It just silently crashes. I have VCRedist2017 x64 installed. According to the Event viewer / Application log this is the issue:

## Event 1
> Faulting application name: orion.exe, version: 1.6.5.0, time stamp: 0x5a9bbd7f
> Faulting module name: Qt5Core.dll, version: 5.8.0.0, time stamp: 0x587fd6c7
> Exception code: 0xc0000005
> Fault offset: 0x00000000001dd793
> Faulting process id: 0x22dc
> Faulting application start time: 0x01d3b93e050d4def
> Faulting application path: C:\Program Files\Orion\bin\orion.exe
> Faulting module path: C:\Program Files\Orion\bin\Qt5Core.dll
> Report Id: d605d475-5cef-40d2-bd5a-1afd91697791
> Faulting package full name: 
> Faulting package-relative application ID: 

## Event 2 
> Fault bucket 1475462102483108258, type 4
> Event Name: APPCRASH
> Response: Not available
> Cab Id: 0
> 
> Problem signature:
> P1: orion.exe
> P2: 1.6.5.0
> P3: 5a9bbd7f
> P4: Qt5Core.dll
> P5: 5.8.0.0
> P6: 587fd6c7
> P7: c0000005
> P8: 00000000001dd793
> P9: 
> P10: 
> 
> Attached files:
> \\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER361B.tmp.dmp
> \\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER3699.tmp.WERInternalMetadata.xml
> \\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER3698.tmp.csv
> \\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER36A8.tmp.txt
> 
> These files may be available here:
> C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_orion.exe_e54d2228f15a206f51c7e537b336c397d281e288_cf0102d8_1fe13cb2
> 
> Analysis symbol: 
> Rechecking for solution: 0
> Report Id: d605d475-5cef-40d2-bd5a-1afd91697791
> Report Status: 268435456
> Hashed bucket: c521df5197babad2d479e4f7020e81a2

## Contents of WER:
> Version=1
EventType=APPCRASH
EventTime=131652487439614678
ReportType=2
Consent=1
UploadTime=131652487442591503
ReportStatus=268435456
ReportIdentifier=7c26bdff-10b7-4082-a6ff-cda34ad502f5
IntegratorReportIdentifier=fa006858-bdc0-40a9-8cb4-e8f284f8d5bf
Wow64Host=34404
NsAppName=orion.exe
AppSessionGuid=00003544-0001-0076-ed27-04623db9d301
TargetAppId=W:00062e478f740c6aa69f841e744d34290d2900000904!000083cce71bbba7bc61f47ea8d86026e6c0ed89cb85!orion.exe
TargetAppVer=2018//03//04:09:33:51!0!orion.exe
BootId=4294967295
ServiceSplit=57
TargetAsId=206
Response.BucketId=9cf1dd273ecfca444c141c2b93e38eab
Response.BucketTable=4
Response.LegacyBucketId=2023273106086530731
Response.type=4
Sig[0].Name=Application Name
Sig[0].Value=orion.exe
Sig[1].Name=Application Version
Sig[1].Value=1.6.5.0
Sig[2].Name=Application Timestamp
Sig[2].Value=5a9bbd7f
Sig[3].Name=Fault Module Name
Sig[3].Value=Qt5Core.dll
Sig[4].Name=Fault Module Version
Sig[4].Value=5.8.0.0
Sig[5].Name=Fault Module Timestamp
Sig[5].Value=587fd6c7
Sig[6].Name=Exception Code
Sig[6].Value=c0000005
Sig[7].Name=Exception Offset
Sig[7].Value=00000000001dd787
DynamicSig[1].Name=OS Version
DynamicSig[1].Value=10.0.15063.2.0.0.256.48
DynamicSig[2].Name=Locale ID
DynamicSig[2].Value=1053
DynamicSig[22].Name=Additional Information 1
DynamicSig[22].Value=8e68
DynamicSig[23].Name=Additional Information 2
DynamicSig[23].Value=8e686ddd5b6531396768d3a922ded1e0
DynamicSig[24].Name=Additional Information 3
DynamicSig[24].Value=b8fd
DynamicSig[25].Name=Additional Information 4
DynamicSig[25].Value=b8fd50944822d8512bb101be98a78350
UI[2]=C:\Program Files\Orion\bin\orion.exe
UI[3]=orion has stopped working
UI[4]=Windows can check online for a solution to the problem.
UI[5]=Check online for a solution and close the program
UI[6]=Check online for a solution later and close the program
UI[7]=Close the program
LoadedModule[0]=C:\Program Files\Orion\bin\orion.exe
LoadedModule[1]=C:\WINDOWS\SYSTEM32\ntdll.dll
LoadedModule[2]=C:\WINDOWS\System32\KERNEL32.DLL
LoadedModule[3]=C:\WINDOWS\System32\KERNELBASE.dll
LoadedModule[4]=C:\WINDOWS\System32\ucrtbase.dll
LoadedModule[5]=C:\WINDOWS\System32\SHELL32.dll
LoadedModule[6]=C:\WINDOWS\System32\msvcrt.dll
LoadedModule[7]=C:\WINDOWS\System32\cfgmgr32.dll
LoadedModule[8]=C:\WINDOWS\System32\shcore.dll
LoadedModule[9]=C:\WINDOWS\System32\RPCRT4.dll
LoadedModule[10]=C:\WINDOWS\System32\combase.dll
LoadedModule[11]=C:\WINDOWS\System32\bcryptPrimitives.dll
LoadedModule[12]=C:\WINDOWS\System32\windows.storage.dll
LoadedModule[13]=C:\WINDOWS\System32\advapi32.dll
LoadedModule[14]=C:\WINDOWS\System32\sechost.dll
LoadedModule[15]=C:\WINDOWS\System32\shlwapi.dll
LoadedModule[16]=C:\WINDOWS\System32\GDI32.dll
LoadedModule[17]=C:\WINDOWS\System32\gdi32full.dll
LoadedModule[18]=C:\WINDOWS\System32\msvcp_win.dll
LoadedModule[19]=C:\WINDOWS\System32\USER32.dll
LoadedModule[20]=C:\WINDOWS\System32\win32u.dll
LoadedModule[21]=C:\WINDOWS\System32\kernel.appcore.dll
LoadedModule[22]=C:\WINDOWS\System32\powrprof.dll
LoadedModule[23]=C:\WINDOWS\System32\profapi.dll
LoadedModule[24]=C:\Program Files\Orion\bin\Qt5Quick.dll
LoadedModule[25]=C:\Program Files\Orion\bin\Qt5Qml.dll
LoadedModule[26]=C:\Program Files\Orion\bin\Qt5Widgets.dll
LoadedModule[27]=C:\WINDOWS\SYSTEM32\VCRUNTIME140.dll
LoadedModule[28]=C:\Program Files\Orion\bin\Qt5Gui.dll
LoadedModule[29]=C:\WINDOWS\System32\ole32.dll
LoadedModule[30]=C:\Program Files\Orion\bin\Qt5Network.dll
LoadedModule[31]=C:\WINDOWS\SYSTEM32\MSVCP140.dll
LoadedModule[32]=C:\WINDOWS\System32\WS2_32.dll
LoadedModule[33]=C:\WINDOWS\System32\CRYPT32.dll
LoadedModule[34]=C:\WINDOWS\System32\MSASN1.dll
LoadedModule[35]=C:\Program Files\Orion\bin\Qt5Core.dll
LoadedModule[36]=C:\WINDOWS\SYSTEM32\dwmapi.dll
LoadedModule[37]=C:\WINDOWS\SYSTEM32\UxTheme.dll
LoadedModule[38]=C:\WINDOWS\SYSTEM32\IPHLPAPI.DLL
LoadedModule[39]=C:\WINDOWS\SYSTEM32\DNSAPI.dll
LoadedModule[40]=C:\WINDOWS\System32\NSI.dll
LoadedModule[41]=C:\WINDOWS\SYSTEM32\MPR.dll
LoadedModule[42]=C:\WINDOWS\SYSTEM32\WINMM.dll
LoadedModule[43]=C:\WINDOWS\SYSTEM32\WINMMBASE.dll
LoadedModule[44]=C:\WINDOWS\System32\IMM32.DLL
LoadedModule[45]=C:\WINDOWS\SYSTEM32\CRYPTBASE.DLL
LoadedModule[46]=C:\Program Files\Orion\bin\platforms\qwindows.dll
LoadedModule[47]=C:\WINDOWS\System32\OLEAUT32.dll
LoadedModule[48]=C:\Program Files\Orion\bin\imageformats\qico.dll
LoadedModule[49]=C:\Program Files\Orion\bin\imageformats\qgif.dll
LoadedModule[50]=C:\Program Files\Orion\bin\imageformats\qicns.dll
LoadedModule[51]=C:\Program Files\Orion\bin\imageformats\qjpeg.dll
LoadedModule[52]=C:\Program Files\Orion\bin\imageformats\qsvg.dll
LoadedModule[53]=C:\Program Files\Orion\bin\Qt5Svg.dll
LoadedModule[54]=C:\Program Files\Orion\bin\imageformats\qtga.dll
LoadedModule[55]=C:\Program Files\Orion\bin\imageformats\qtiff.dll
LoadedModule[56]=C:\Program Files\Orion\bin\imageformats\qwbmp.dll
LoadedModule[57]=C:\Program Files\Orion\bin\imageformats\qwebp.dll
LoadedModule[58]=C:\Program Files\Orion\bin\bearer\qgenericbearer.dll
LoadedModule[59]=C:\WINDOWS\SYSTEM32\dhcpcsvc.DLL
LoadedModule[60]=C:\WINDOWS\SYSTEM32\dhcpcsvc6.DLL
LoadedModule[61]=C:\Program Files\Orion\bin\bearer\qnativewifibearer.dll
LoadedModule[62]=C:\WINDOWS\SYSTEM32\wlanapi.dll
LoadedModule[63]=C:\Program Files\Orion\bin\ssleay32.dll
LoadedModule[64]=C:\WINDOWS\SYSTEM32\MSVCR120.dll
LoadedModule[65]=C:\Program Files\Orion\bin\LIBEAY32.dll
LoadedModule[66]=C:\WINDOWS\SYSTEM32\bcrypt.dll
LoadedModule[67]=C:\WINDOWS\SYSTEM32\CRYPTSP.dll
LoadedModule[68]=C:\WINDOWS\system32\rsaenh.dll
LoadedModule[69]=C:\WINDOWS\system32\winhttp.dll
LoadedModule[70]=C:\WINDOWS\SYSTEM32\SspiCli.dll
LoadedModule[71]=C:\WINDOWS\system32\napinsp.dll
LoadedModule[72]=C:\WINDOWS\system32\pnrpnsp.dll
LoadedModule[73]=C:\WINDOWS\system32\NLAapi.dll
LoadedModule[74]=C:\WINDOWS\System32\mswsock.dll
LoadedModule[75]=C:\WINDOWS\System32\winrnr.dll
LoadedModule[76]=C:\Program Files\Bonjour\mdnsNSP.dll
LoadedModule[77]=C:\Windows\System32\rasadhlp.dll
LoadedModule[78]=C:\WINDOWS\System32\fwpuclnt.dll
LoadedModule[79]=C:\Program Files\Orion\bin\QtQuick.2\qtquick2plugin.dll
LoadedModule[80]=C:\Program Files\Orion\bin\QtQuick\Window.2\windowplugin.dll
LoadedModule[81]=C:\Program Files\Orion\bin\QtQuick\Controls.2\qtquickcontrols2plugin.dll
LoadedModule[82]=C:\Program Files\Orion\bin\Qt5QuickControls2.dll
LoadedModule[83]=C:\Program Files\Orion\bin\Qt5QuickTemplates2.dll
LoadedModule[84]=C:\Program Files\Orion\bin\QtQuick\Controls.2\Material\qtquickcontrols2materialstyleplugin.dll
LoadedModule[85]=C:\WINDOWS\system32\dwrite.dll
LoadedModule[86]=C:\Program Files\Orion\bin\QtQuick\Layouts\qquicklayoutsplugin.dll
LoadedModule[87]=C:\Program Files\Orion\bin\QtQuick\Templates.2\qtquicktemplates2plugin.dll
LoadedModule[88]=C:\Program Files\Orion\bin\QtGraphicalEffects\qtgraphicaleffectsplugin.dll
LoadedModule[89]=C:\Program Files\Orion\bin\QtGraphicalEffects\private\qtgraphicaleffectsprivate.dll
LoadedModule[90]=C:\Program Files\Orion\bin\Qt\labs\platform\qtlabsplatformplugin.dll
State[0].Key=Transport.DoneStage1
State[0].Value=1
FriendlyEventName=Stopped working
ConsentKey=APPCRASH
AppName=orion
AppPath=C:\Program Files\Orion\bin\orion.exe
NsPartner=windows
NsGroup=windows8
ApplicationIdentity=BD3774FC0660C3E4C735100DA460A6DA
MetadataHash=1572229918

**Comment by ahjolinna** [comment]
why is the windows version using Qt5.8?! which is so BROKEN release even Qt admitted this and didn't even bother to release 5.8.1 to patch it because it was so broken they wanted to focus on 5.9 100% instead.

so maybe use 5.9.4 at least which is the latest LTS, or 5.10.1 that has been a really nice release (and a solid one)

**Comment by fehrm** [comment]
I don't know if you are asking rhetorical questions 😄 ? Just so I have it said, I don't have QT installed on my machine. I only use the ones supplied by Orion.

**Comment by rakslice** [comment]
See my comments on https://github.com/alamminsalo/orion/issues/180 .  The pull request there has already been merged, but need some guidance from @alamminsalo to maybe recommend a codec to use this with if it worked in testing?

**Comment by alamminsalo** [comment]
I think we need to revert to mpv. Qt multimedia requires manually installing codecs to work

**Comment by mrgreywater** [comment]
Should be fixed with #251, release 1.66

**Comment by fehrm** [comment]
Sorry, I didn't close this issue. Yes it is fixed with 1.6.6. I run the mpv version and it runs beautifully now!
