### ISSUE TITLE
time to move away from github?

### ISSUE THREAD

**Issue by ahjolinna** [alamminsalo/orion#238]
Microsoft Is Said to Have Agreed to Acquire Coding Site GitHub https://developers.slashdot.org/story/18/06/03/2042255/microsoft-is-said-to-have-agreed-to-acquire-coding-site-github

I don't know how you feel about this personally but there is a huge wave of backlash against this and many are already migrating to gitlab (or others)

**Comment by ahjolinna** [comment]
I really hope this is a coincidence: https://www.gentoo.org/news/2018/06/28/Github-gentoo-org-hacked.html

**Comment by alamminsalo** [comment]
I'm sure some people think controversially about ms buying github, but I've grown too customed to using github and tbh many projects that moved have to keep a mirror at least because the community is still here. I don't currently have any plans for that
