### ISSUE TITLE
Default Window Size is too small

### ISSUE THREAD

**Issue by imanrp** [alamminsalo/orion#247]
This is just a minor issue, it happens on my Manjaro Linux **XFCE** Edition, I installed Orion from AUR (version 1.6.5-3) 
![orion_2018-10-07_16-03](https://user-images.githubusercontent.com/2027300/46580238-30823e00-ca4b-11e8-952d-4f20c7f11a5f.png)

The app open up that small when I first launch it. It would be nice if the default size is at least maybe 800x600 pixels.

**Comment by ForLoveOfCats** [comment]
Same issue on Manjaro KDE Plasma 5
![image](https://user-images.githubusercontent.com/30666851/46586429-46dcc980-ca4c-11e8-87a3-0880bc91b9f3.png)

**Comment by ForLoveOfCats** [comment]
I rebuilt from master and no longer experience this bug. It appears this commit fixed it: https://github.com/alamminsalo/orion/commit/ce0ac00e830629ef2dde0634f6cdff2d0e1a3842

**Comment by imanrp** [comment]
Great news!
