### ISSUE TITLE
add CUVID/CUDA hardware hardware acceleration for Nvidia

### ISSUE THREAD

**Issue by ahjolinna** [alamminsalo/orion#248]
Nvidia had deprecated VDPAU years ago in favor of their new CUDA based cuvid (which is crossplatform), so it would be good to have this on orion.

**Comment by mrgreywater** [comment]
I don't have a nvidia graphics card, but CUDA should be available with both the mpv and qtav backend.

**Comment by ahjolinna** [comment]
I have the latest git version and I can only choose between vaapi and vdpau or auto.. no cuvid.

I use mpv backend version on openSUSE.. From my own repo (and yes mpv has cuda/cuvid enabled... As I use it just fine on mpc-qt)

**Comment by mrgreywater** [comment]
if you want to manually choose it, you can add nvdec-copy and cuda-copy here: https://github.com/alamminsalo/orion/blob/master/src/qml/MpvBackend.qml#L114

auto should already work though, if mpv thinks it's the best option for you, auto might use nvdec/cuda already. Sadly mpv doesn't support sharing those cuda surfaces with opengl, and therefore needs to do a costly copy via system memory.

**Comment by ahjolinna** [comment]
Also it's vaapi/vdpau -copy and some people have problems with that option.. At least on Linux

**Comment by mrgreywater** [comment]
You can try using the non -copy versions, but afaik mpv doesn't support any of them with the opengl-cb video decoder or render api. This is an issue with mpv and not with orion.

**Comment by ahjolinna** [comment]
I don't care personally about the -copy I just remember that it can cause issues with some.... I just wanted to mention that vdpau has  been replaced with cuvid (long time ago)

**Comment by mrgreywater** [comment]
Should be fixed with #252

**Comment by mrgreywater** [comment]
The PR has been merged, I think this can be closed.
