### ISSUE TITLE
(experimental/optional) vulkan support

### ISSUE THREAD

**Issue by ahjolinna** [alamminsalo/orion#249]
I really don't know if there will be any real performance benefits over OpenGL but as at least Qt5 and MPV does support it, I think it would be nice to have it for those who want to try it out.....at least the driver (support) is better...and Android did moved to Vulkan (if alamminsalo cares about android version anymore)

**Comment by mrgreywater** [comment]
Orion draws the ui with Qt Quick/QML which in turn is rendered with OpenGL. Once Qt has a vulkan renderer for Qt Quick, so will Orion.
As for the video hardware decoding, I doubt it makes a difference in performance, since that's not really a draw call heavy workload.

**Comment by ahjolinna** [comment]
Oh, I didn't remember if the Vulkan support included qml.

Okay yes maybe the UI wouldn't never get any real benefits but maybe option for mpv (at least) would be good

**Comment by mrgreywater** [comment]
The only available api type of the mpv render api is OpenGL, see https://github.com/mpv-player/mpv/blob/master/libmpv/render.h#L327

And more importantly, it doesn't even allow zero copy hardware acceleration right now (at least not on windows), which is far more important than supporting vulkan.
