### ISSUE TITLE
flatpak or snap pkgs?

### ISSUE THREAD

**Issue by ahjolinna** [alamminsalo/orion#25]
have you thought about making/supporting some of these "sandbox pkg formats" like [flatpak](http://flatpak.org/) or [snap](http://snapcraft.io/)..there is also [AppImage](http://appimage.org/)...but who cares

I would personally go with flatpak because its xdg standard, snap is from Canonical so you will never know what will happen

**Comment by alamminsalo** [comment]
I am planning for doing flatpak packages

**Comment by probonopd** [comment]
...or linuxdeployqt

**Comment by alamminsalo** [comment]
Thanks, I'll check that out

**Comment by alamminsalo** [comment]
Uploaded AppImage release build using these tips, thanks

**Comment by probonopd** [comment]
> Uploaded AppImage release build using these tips, thanks

Very cool @alamminsalo, unfortunately we are running into an issue which I am confident we can solve together: https://github.com/alamminsalo/orion/issues/48
