### ISSUE TITLE
orion(-git) won't build

### ISSUE THREAD

**Issue by ahjolinna** [alamminsalo/orion#253]
I tried to make a build for openSUSE (tumbleweed) using OBS, and it fails

```
[   99s] /usr/include/c++/8/bits/predefined_ops.h: In instantiation of 'bool __gnu_cxx::__ops::_Iter_pred<_Predicate>::operator()(_Iterator) [with _Iterator = __gnu_cxx::__normal_iterator<std::unique_ptr<QJSValue>*, std::vector<std::unique_ptr<QJSValue> > >; _Predicate = MpvObject::unobserveProperty(const QJSValue&)::<lambda(const int&)>]':
[   99s] /usr/include/c++/8/bits/stl_algo.h:869:13:   required from '_ForwardIterator std::__remove_if(_ForwardIterator, _ForwardIterator, _Predicate) [with _ForwardIterator = __gnu_cxx::__normal_iterator<std::unique_ptr<QJSValue>*, std::vector<std::unique_ptr<QJSValue> > >; _Predicate = __gnu_cxx::__ops::_Iter_pred<MpvObject::unobserveProperty(const QJSValue&)::<lambda(const int&)> >]'
[   99s] /usr/include/c++/8/bits/stl_algo.h:939:30:   required from '_FIter std::remove_if(_FIter, _FIter, _Predicate) [with _FIter = __gnu_cxx::__normal_iterator<std::unique_ptr<QJSValue>*, std::vector<std::unique_ptr<QJSValue> > >; _Predicate = MpvObject::unobserveProperty(const QJSValue&)::<lambda(const int&)>]'
[   99s] src/player/mpvobject.cpp:196:6:   required from here
[   99s] /usr/include/c++/8/bits/predefined_ops.h:283:11: error: no match for call to '(MpvObject::unobserveProperty(const QJSValue&)::<lambda(const int&)>) (std::unique_ptr<QJSValue>&)'
[   99s]   { return bool(_M_pred(*__it)); }
[   99s]            ^~~~~~~~~~~~~~~~~~~~
[   99s] src/player/mpvobject.cpp:189:90: note: candidate: 'MpvObject::unobserveProperty(const QJSValue&)::<lambda(const int&)>'
[   99s]      callbacks.erase(std::remove_if(callbacks.begin(), callbacks.end(), [&](auto const& cb){
[   99s]                                                                                           ^
[   99s] src/player/mpvobject.cpp:189:90: note:   no known conversion for argument 1 from 'std::unique_ptr<QJSValue>' to 'const int&'
[   99s] /usr/lib64/qt5/bin/moc -DAPP_VERSION=\"v1.6.6+git~20181015-147.1\" -DAPP_NAME=\"Orion\" -DMPV_PLAYER -DPLAYER_BACKEND=\"mpv\" -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_QUICKCONTROLS2_LIB -DQT_QUICK_LIB -DQT_GUI_LIB -DQT_QML_LIB -DQT_NETWORK_LIB -DQT_DBUS_LIB -DQT_CORE_LIB --include '/home/abuild/rpmbuild/BUILD/orion-1.6.6+git~20181015/moc_predefs.h' -I/usr/lib64/qt5/mkspecs/linux-g++ -I'/home/abuild/rpmbuild/BUILD/orion-1.6.6+git~20181015' -I/usr/include/qt5 -I/usr/include/qt5/QtWidgets -I/usr/include/qt5/QtQuickControls2 -I/usr/include/qt5/QtQuick -I/usr/include/qt5/QtGui -I/usr/include/qt5/QtQml -I/usr/include/qt5/QtNetwork -I/usr/include/qt5/QtDBus -I/usr/include/qt5/QtCore -I/usr/include/c++/8 -I/usr/include/c++/8/x86_64-suse-linux -I/usr/include/c++/8/backward -I/usr/lib64/gcc/x86_64-suse-linux/8/include -I/usr/local/include -I/usr/lib64/gcc/x86_64-suse-linux/8/include-fixed -I/usr/x86_64-suse-linux/include -I/usr/include src/network/networkmanager.h -o moc_networkmanager.cpp
[   99s] make: *** [Makefile:954: mpvobject.o] Error 1
[   99s] make: *** Waiting for unfinished jobs....
[  103s] error: Bad exit status from /var/tmp/rpm-tmp.K15KRK (%build)
[  103s] 
[  103s] 
[  103s] RPM build errors:
[  103s]     Bad exit status from /var/tmp/rpm-tmp.K15KRK (%build)

```

https://build.opensuse.org/package/show/home:ahjolinna/orion

the whole build log file : [link](https://paste.kde.org/prx1isc5b/9yrnzb/raw)

**Comment by ahjolinna** [comment]
@mrgreywater it was after this got merged https://github.com/alamminsalo/orion/pull/252

**Comment by mrgreywater** [comment]
That code is valid c++11. Both the osx and windows build are compiling, see appveyor and travis ci. Whichever compiler you're using doesn't seem to deduce the auto type correctly. Maybe try using another (maybe newer?) version of your compiler with the `-std=c++11`, I'll look into adding a linux build in travis and add a appimage artifact.

**Comment by ahjolinna** [comment]
@mrgreywater : I use [openSUSE OBS](https://build.opensuse.org/) to build my pkgs, and it support many linux distros ..not just SUSE, for example [SailfishOS](https://sailfishos.org/wiki/Open_Build_Service) / [mer](https://wiki.merproject.org/wiki/Building_against_Mer_in_Community_OBS) use it and oc many other

OBS: https://openbuildservice.org

**Comment by ahjolinna** [comment]
also I use default GCC(++), I haven't tried clang/llvm (which I do like more)

**Comment by mrgreywater** [comment]
Thanks for showing me Clazy, but this is not a code issue, this is a build configuration issue. As I said, I'll look into it soon.

**Comment by ahjolinna** [comment]
I got that, but I just wanted to mention Clazy as a tip at least

**Comment by ahjolinna** [comment]
@mrgreywater I added that 'patch' and i get this build error now with openSUSE [leap 15 ](https://paste.kde.org/pzzkxcdfs/1d4rq9/raw), but the tumbleweed (rolling) version did build just fine

**Comment by ahjolinna** [comment]
@mrgreywater : I tried adding openssl (or/and libopenssl1_0_0) and the leap 15 (with Qt5.9) still fails to build

**Comment by mrgreywater** [comment]
Openssl is a runtime dependency for Qt, not build time. Shouldn't make a difference. As I tried to explain previously, just make sure you have c++14 enabled in the orion.pro file (like in the PR) and use a compiler that is suitable such as gcc5+ (I use gcc7). It compiles fine, see travis: https://travis-ci.org/mrgreywater/orion/jobs/442697645 and the AppImage https://github.com/mrgreywater/orion/releases/tag/1.6.6-test2

**Comment by mrgreywater** [comment]
Sorry, I didn't see that hidden second error log there: https://paste.kde.org/pzzkxcdfs/1d4rq9/raw

```
-I/usr/lib64/qt5/mkspecs/linux-g++ -o channellistmodel.o src/model/channellistmodel.cpp
[   49s] In file included from src/main.cpp:43:0:
[   49s] src/player/mpvobject.h:10:10: fatal error: mpv/render_gl.h: No such file or directory
[   49s]  #include <mpv/render_gl.h>
[   49s]           ^~~~~~~~~~~~~~~~~
[   49s] compilation terminated.
[   49s] make: *** [Makefile:791: main.o] Error 1
```

This just means your libmpv-dev package is out of date. mpv added a new api and deprecated their old one, so you need to either find an up-to-date libmpv build, or compile your own (see [ci/build_mpv.sh](https://github.com/alamminsalo/orion/pull/258/files#diff-af7e499dead4f87c1d8cb98b49adf6c2) )

**Comment by ahjolinna** [comment]
@mrgreywater : well unfortunately mpv 0.28.x requires ffmpeg4.x and leap 15 has the older 3.4.4 and so does many other LTS distros, so do you think it would be possible to add "backwards compatibility" for those users?

because I don't think adding ffmpeg4 would work (or at least an ideal solution) as it could break the distro or at least many other apps, yes I could pkgs so that you can have both version....but still.

**Comment by mrgreywater** [comment]
Similarly to what I do in travis, you could potentially use these scripts https://github.com/mpv-player/mpv-build to compile and build ffmpeg and libmpv to a static library, so they are all included in the final orion binary. Alternatively compile ffmpeg static, and mpv shared, and distribute your own up-to-date libmpv package for openSUSE. Adding back support for the old deprecated API is not the right solution imo.

**Comment by ahjolinna** [comment]
personally I do hate that both ffmpeg and mpv keep breaking their APIs so much/easily (just plain laziness and lack of discipline).
Also do think sad that LTS distros can loose support of some apps because of this. Having two version of ffmpeg/mpv isn't an ideal or good solution, just because it works it doesn't mean it you should do it...just a lazy way out of a problem

for now orion is part of the official suse repos I wonder if openSUSE team will remove the leap 15 version because of this(same with or other LTS distros)...or either they may keep the old version as long as it works and then remove it

**Comment by mrgreywater** [comment]
Well it's the genesis of mpv to [remove old parts](https://github.com/mpv-player/mpv/wiki/FAQ#How_is_mpv_related_to_MPlayer) and only keep what's new and actually needed. And to their defense, they haven't actually removed the old api, just deprecated it.

Personally I also think the real problem here is that those distributions don't keep their packages updated, and keep distributing old packages, even if there doesn't seem to be any reason to do so.

Anyway, I'll back the old code with a mpv version check.

**Comment by ahjolinna** [comment]
well at least with openSUSE leap ([15 forward](https://news.opensuse.org/2018/05/25/based-on-enterprise-code-tested-millions-of-times-opensuse-leap-15-released/)) it does share it core pkgs with SUSE enterprise, so this is one of the reason why those pkgs won't get any major updates ...for the other LTS distros it also just comes down to having a well tested system.

personally I like the "[semi-rolling](https://en.wikipedia.org/wiki/Rolling_distribution#Part-rolling.2C_semi-rolling.2C_or_half-rolling_distributions)" update model the most, it's what for example chakraOS is using.....I think Jolla's [SailfishOS](http://sailfishos.org/) kinda uses that model ...and with [mer](http://merproject.org/) as their "rolling" base

**Comment by ahjolinna** [comment]
@XenonPK any input?

**Comment by ahjolinna** [comment]
@mrgreywater : thanks, it builds now...so I will close this
