### ISSUE TITLE
Chat not working on OS X

### ISSUE THREAD

**Issue by link82** [alamminsalo/orion#27]
I'm trying you client on OSX - El Capitan, it works great except for the chat: it doesn't show any message at all.

Let me know if I can provide more details about it.

Thanks!

**Comment by alamminsalo** [comment]
Currently chat only works if you are logged in, but anonymous chat reading is on the todo-list

**Comment by link82** [comment]
I was logged in: I've also tried different streamers to check if this issue is related to a specific one (maybe if they're using any kind of addon / bot or anything that can cause problems)

**Comment by alamminsalo** [comment]
Just popped out a new release. Check if this fixes your problem

**Comment by link82** [comment]
Yes! It's now working properly.
Thank you!
