### ISSUE TITLE
Player now always serving ads

### ISSUE THREAD

**Issue by ROBOKiTTY** [alamminsalo/orion#279]
Running prebuilt 1.6.1 on Windows.

Not sure if twitch changed something on their end this week, but starting a stream now always results in an ad playing before the stream. This happens regardless of whether I'm starting a stream from the other tabs or clicking refresh in the player.

**Comment by rakslice** [comment]
Yeah, they implemented preroll ads on all the streams they serve, including the ones that orion uses, probably to go along with the end of ad-free viewing for twitch prime subscribers https://blog.twitch.tv/en/2018/08/20/changes-to-twitch-prime-a986f0d8c9a9/
