### ISSUE TITLE
COPR package is missing a dependency on qt5-quickcontrols

### ISSUE THREAD

**Issue by davidcl** [alamminsalo/orion#28]
Without any KDE / QT libraries, I installed orion using the COPR package and got an error at startup : 
```
$ orion
QQmlApplicationEngine failed to load component
qrc:/main.qml:17 module "QtQuick.Controls" is not installed
```
After installing `qt5-qtquickcontrols` it started.

**Comment by alamminsalo** [comment]
You should probably give this information to the one running the COPR, since I don't currently have any repos in aur or copr
