### ISSUE TITLE
New release ?

### ISSUE THREAD

**Issue by ddup1** [alamminsalo/orion#289]
Hi,

As you merged change for new api key, will you create a new release ? I need it :)

Regards.

**Comment by ddup1** [comment]
Ok, it seems that CI failed to pull merged version.

**Comment by woowoots** [comment]
it mean still no new version ? :(

**Comment by alamminsalo** [comment]
I have just fixed CI issues and put up a new release 1.6.7

**Comment by woowoots** [comment]
Oh that's nice, i wasnt checking at the right place to see the lastest version ! thanks for the update !
