### ISSUE TITLE
[question] opensuse LEAP 42.2 / Qt5.6.1

### ISSUE THREAD

**Issue by ahjolinna** [alamminsalo/orion#30]
I just installed/switched to the new [openSUSE leap 42.2](https://news.opensuse.org/2016/11/16/optimal-release-for-linux-professionals-arrives-with-opensuse-leap-42-2/) -kde and it uses [Qt5.6.1](https://blog.qt.io/blog/2016/06/08/qt-5-6-1-released/) (LTS), as orion seems to require 5.7+ (mandatory requirement?) I was wondering how I can get it installed? 
also the problem is that I'm no RPM expert I havent been using RPM/opensuse in over 5 years now.

flatpak could be an option, but its not support in leap offically only in the tumbleweed version (rolling version), oc you can always install some unoffical version.

thought I have notice with many proprietary apps (discord, franz, spotify, svp, viber) that using a pre-compiled binary works just fine, maybe that could be an option?

----

I will reinstall chakraOS on my 2nd SSD when the new ISO arrives, for mainly testing usage.

Why I switched to opensuse leap? well I wanted a solid KDE distro and when I hate ubuntu/deb based distros ...they aren't an option...and fedora isnt for normal desktop usage, at least from gaming perspective, so openSUSE leap is the best middle ground

**Comment by ahjolinna** [comment]
okay it seems to compile, BUT I needed to add (lib)Qt5DBus and (lib)Qt5OpenGL (-devel) dependencies for it even compile

**Comment by ahjolinna** [comment]
it seems gstreamer ugly plugin/codec is need, I also found a problem if you have the gst-vaapi plugin installed also and you have a nvidia system the videoplayback wont work I got this gdb output: http://pastebin.com/RZtr42bH

if you are intrested here is the gdb output before I had the gst plugins installed: http://pastebin.com/fVUsmhBU

PS. I installed the git version, so my does it install the orion binary to "/usr/bin/orion" ? I think it would be better that it would be in "/opt/orion/orion" ...at least the git version (opt is a place to install "foreign" packages not part of the Operating System)  http://www.pathname.com/fhs/pub/fhs-2.3.html#OPTADDONAPPLICATIONSOFTWAREPACKAGES

**Comment by ahjolinna** [comment]
Some errors (will update as they arrive) ;

[175200.631666] traps: orion[11458] general protection ip:7f9a97b21804 sp:7ffdae9c5238 error:0 in libQt5Core.so.5.6.1[7f9a97887000+4ae000]traps:

**Comment by zabuldon** [comment]
Hi, can you try build with latest sources? 
If the issue still there, i'll install openSUSE and try to find cause.

**Comment by ahjolinna** [comment]
already have (few times) and no noticeable changes, I also rebuilded yesterday to try if it would somehow help with the issue #34 ...no, sigh maybe I have to uninstall the codec pack....anyway back to playing [FFXV](https://www.youtube.com/watch?v=yqpf488XPO0)

**Comment by XenonPK** [comment]
I have successfully compiled it using the mpv backend for OpenSUSE Tumbleweed and both versions of LEAP. I have tested it on Tumbleweed, and made it available as rpm. If you would like to install and test the rpms , [Here's](https://software.opensuse.org/download.html?project=home%3Axenonpk&package=orion) the link. It's working perfectly on my Tumbleweed machine, BTW.

**Comment by ahjolinna** [comment]
@XenonPK : thats nice, but to late for me as I got banned from their IRC channel and I left openSUSE after I told them how incomptent their distro is when it comes to (default) codecs and drivers (and few other things) more about it here: https://github.com/alamminsalo/orion/issues/34#issuecomment-267090343

ps. it would be better if you went "pure Qt5" aka use the qt5-multimedia instead (and I think gst-ugly-plugin is needed for playback) as it works better than mpv. The mpv doesn't work well with livestreams....well its ffmpeg problem mostly
