### ISSUE TITLE
Keep Settings

### ISSUE THREAD

**Issue by cadox8** [alamminsalo/orion#32]
I would like to keep my settings when closed and open Orion (Settings and volume).
Also, a background play (Close windows and follow playing the stream) should be great :D

**Comment by zabuldon** [comment]
I think it already implemented.

**Comment by cadox8** [comment]
In mine, every time i open it, settings was resetted

**Comment by zabuldon** [comment]
Hello again,
I have done some changes. 
Can you try to build Orion from this branch https://github.com/zabuldon/orion/tree/QSettings and test if setting are saved?

**Comment by cadox8** [comment]
Yeah, it works fine now, thank you :D
