### ISSUE TITLE
show preview when mouse hovers on seek bar for VOD's

### ISSUE THREAD

**Issue by ahjolinna** [alamminsalo/orion#35]
I don't if this is feasible on VOD's, but it would be nice to see a small preview when you put your mouse on the seek bar, at least there have been times when you need/like to find and start from a specific spot ....there are also other reasons reasons or another why this is nice...

I really don't care if it shows the nearest keyframe instead of exact frame, also you could add the current timerange/timestamp thing under the "preview img"

**Comment by zabuldon** [comment]
I'm not sure if preview can be implemented without issues, but I'll check,.
