### ISSUE TITLE
stream video arent "smooth"

### ISSUE THREAD

**Issue by woowoots** [alamminsalo/orion#43]
maybe its "connected" to the recent stream stop / "lag" issues.
But stream video arent smooth anymore, it feel "laggy"

watch the stream on orion & twitch at the same time, the difference is very noticiable :( 

No idea what's wrong

**Comment by ahjolinna** [comment]
@woowoots : what do you mean laggy? do you mean there is buffering problem or the playback keeps dropping frames? also what OS/distro do you have and GPU/driver, plus what backend are you using on orion (qt-multimedia, mpv or qtav)...

if you use linux and mpv backend, try using the qt-multimedia (+gstreamer1.x "ulgy"-plugin), as it should work....if u are already using them, have u tried to recompile? and/or are using the git version? if not, try it

**Comment by woowoots** [comment]
I meant, its like there is a very inconsistent frametime - stutter ( dont know how to really explain that ). But the "playback" also randomly just stop, i have to reload - restart Orion
Same goes for the chat that sometime just dont keep up. And if i type sometime, it catch up ( like 30+message appear at the same time, or i do have to change stream - go back to where i was to have the chat work again )

I'am on win10 64bit, i have a gtx1070 with the 376.19 drivers

what do you mean by "what backend" i'am i using ? I just have the codecs x264 vfw installed. ( if that what you are asking :o )

**Comment by ahjolinna** [comment]
okay so its win10 problem, so that probably means that its using MPV for backend as its the default option, do you have the latest orion installed? aka  v.1.3.5 (or do u have the git version?) also do you have the latest MPV installed? aka [v0.23.0](https://github.com/mpv-player/mpv/releases/tag/v0.23.0)

btw. it seems you have an old nvidia driver the latest one is [378.49 (WHQL)](http://www.nvidia.com/download/driverResults.aspx/114351/en-us)

I personally can't really help or test as I don't use windows anymore, maybe the dev (@alamminsalo)  can help with this.

**Comment by woowoots** [comment]
I dont see why it would be a win10 issue, since thoses issues are quite recent.
Maybe twitch changed something ? so orion have issues ?

I have the 1.3.5, isnt the git version the same ? 

Why would i install MPV i doesnt  have / never had  in the first place ? :o

**Comment by ahjolinna** [comment]
I'm not sure how the Windows version is built (no direct info available) , but orion supports mpv(default), qtav and qt-multimedia as the backend player's... And when mpv is the default option I assumed that it was needed.

And it seems likely that it's a just windows problem as it works fine for me on Linux...thought I do use the git version instead, I will try the stable version soon.. 

And what I mean with git version is the latest “development/unstable “ version that you have to compile yourself, the one you're using is the latest "stable" version which is pre-compiled

**Comment by woowoots** [comment]
I have no idea how to compile things myself otherwise, sure i would give a try a the git version oO

**Comment by alamminsalo** [comment]
Orion on windows uses QtAV as backend

**Comment by ahjolinna** [comment]
Qtav?! Really that would have been my last guess, why not qt-multimedia...okay depends how it works

Anyways it would be nice for Windows/Mac user to have small guide/tutorial how to build at least the git version, so more cross-platform testing could happen

**Comment by woowoots** [comment]
Well, i tried several things
- install the lastest nvidia drivers
- uninstall / re-install another software i updated last day ( just in case it was creating somes issues )
- uninstall / re-install orion ( the .exe, i still dont know how to install the github version )

And ofc, nothing helped, stream are still utterly broken. Playback stop - freeze very often. No idea what i could / should do ( if its really an issue on my side )

**Comment by alamminsalo** [comment]
Building on windows is a bit fiddly because various reasons (mpv doesnt compile with msvc, and qt's webengine doesn't compile with mingw-gcc). It's a bit easier to use qtav there

**Comment by ahjolinna** [comment]
well maybe MPV should separate? and up to the user to have it installed ...there are [pre-compiled versions ](https://mpv.io/installation), or have installer which will install it.

[windows compilation instruction ](https://github.com/mpv-player/mpv/blob/master/DOCS/compile-windows.md)

as for the webengine issue, what version of mingw-gcc did u try? The minimum version of MinGW-builds supported is GCC 4.9.1

http://doc.qt.io/qt-5/windows-requirements.html
http://doc.qt.io/qt-5/supported-platforms-and-configurations.html
http://doc.qt.io/qt-5/qtwebengine-platform-notes.html

**Comment by alamminsalo** [comment]
I have just updated windows installer (1.4.0). It's built with mpv backend now. If this fixes your playback problems you can close this issue

**Comment by woowoots** [comment]
tried the 1.4.0 since a while now, and saddly still have thoses playback stop, as for the "smooth" video, that appear to be fine now
