### ISSUE TITLE
 could not find or load the Qt platform plugin "xcb"

### ISSUE THREAD

**Issue by probonopd** [alamminsalo/orion#48]
Getting this error on Ubuntu 16.04:

```
me@host:~$ /home/me/Downloads/Orion-1.4.1.AppImage 
This application failed to start because it could not find or load the Qt platform plugin "xcb"
in "".

Available platform plugins are: xcb.

Reinstalling the application may fix this problem.
Aborted

```

**Comment by probonopd** [comment]
Appears to eb caused by the application trying to load `libQt5XcbQpa.so.5` from the system rather than from inside the AppImage, as running it with `LD_DEBUG=libs ...` shows:

```
/usr/lib/x86_64-linux-gnu/libQt5XcbQpa.so.5: error: version lookup error: version `Qt_5_PRIVATE_API' not found (required by /mnt/plugins/platforms/libqxcb.so) (fatal)
```

Question is why it is not using the `libQt5XcbQpa.so.5` from inside the AppImage.
Please try running `linuxdeployqt` twice on the same application, and let me know if this solves it.

**Comment by alamminsalo** [comment]
Tried to run it few times, it seems I can't get it fixed by running few times.
Also I'm getting loads of this error during linuxdeployqt: `ERROR: ldd outputLine: "\tlibsamba-debug-samba4.so => not found"`. Could this be related?

**Comment by probonopd** [comment]
Hard to say, possibly. Which host system (distribution and version) are you running linuxdeployqt on?

**Comment by alamminsalo** [comment]
I'm running on arch linux. The qt version is installed from the repo (5.9). I guess I could try the official downloadable version tomorrow

**Comment by alamminsalo** [comment]
Okay so I figured it out. The libqxcb.so rpath hadn't been set correctly. Running `patchelf --set-rpath '$ORIGIN/../../lib' plugins/platforms/libqxcb.so` fixed that. After that, I figured `libexec/QtWebEngineProcess` was also missing rpath set to AppImages' `/lib` path, so I set the path there by `patchelf --set-rpath '$ORIGIN/../lib`

**Comment by mohdumar644** [comment]
Having the same issue.

My AppImage seems to find xcb in the temporary mount but can't load it, for the same reason that it is trying to pick `libQt5XcbQpa.so.5` from the system (which is a different version of Qt). 

My target system is Raspbian jessie.

**Comment by probonopd** [comment]
Thanks for figuring this out, really helpful. Can you find out why it hadn't been patched properly by linuxdeployqt, and propose a patch? That'd be awesome!

**Comment by alamminsalo** [comment]
Glad to help, but sadly I have no clue about why it wasn't patched properly or how to automate the fix

**Comment by probonopd** [comment]
Please retry with the latest continuous build of linuxdeployqt. https://github.com/probonopd/linuxdeployqt/commit/b71bd4d587051c2e543b08a3951cb9d2ee36c0c3 and https://github.com/probonopd/linuxdeployqt/commit/bace185665b3738cfc875a04edfa16998a06997c may have fixed this.

**Comment by ShnitzelKiller** [comment]
I am now having this same issue, and the posted fix does not work.

**Comment by probonopd** [comment]
@ShnitzelKiller please link to the exact AppImage that is giving you this issue so that I can analyze it. Thanks!

**Comment by s-d-m** [comment]
Hi @probonopd 

I got the same issue.
The resulting binary is available at https://github.com/s-d-m/github_as_free_public_storage/blob/master/lilyplayer-x86_64_fails_requires_Qt_platform_plugin_xcb.AppImage

If it helps, it was compiled on debian unstable, using g++-8. If you want to compile it yourself, and try different compile options, the sources are available at https://github.com/s-d-m/lilyplayer

For the linuxqtdeploy I used, I took one from the "continuous build" release.
`linuxdeployqt 4 (commit ac2d5c2), build 561 built on 2018-07-09 18:54:52 UTC`

When running the binary with 'LD_DEBUG=libs' it shows that it looks to the normal filesystem:
```
     32414:     find library=libxcb.so.1 [0]; searching
     32414:      search cache=/etc/ld.so.cache
     32414:       trying file=/usr/lib/x86_64-linux-gnu/libxcb.so.1
```
Note: libxcb is not the only one here. For the full logs of what gets printed when running LD_DEBUG=libs ./the_appimage, see https://github.com/s-d-m/github_as_free_public_storage/blob/master/log_LD_DEBUG_lib_when_running_lilyplayer_appimage

**Comment by probonopd** [comment]
@s-d-m please see https://github.com/s-d-m/lilyplayer/issues/2

**Comment by s-d-m** [comment]
I made a "small app" which compiles on ubuntu 14.04.

you would have to install first `libqt5widgets5 libqt5gui5 libqt5core5a qt5-default qt5-qmake realpath wget g++` on it first

when running the generated appimage (made with make appimage), the libxcb is still taken from the outside world (at least accord do the LD_DEBUG=libs output).

you can get that small app at https://github.com/s-d-m/github_as_free_public_storage/blob/master/minimum_failing_app_for_linuxqtdeploy.tar.bz2
