### ISSUE TITLE
scrolling anywhere affects audio volume lvl

### ISSUE THREAD

**Issue by ahjolinna** [alamminsalo/orion#49]
so if I start to scroll anywhere in orion it also affects the audio's volume level, its really annoying when you scroll down and the audio mutes.

-------

also it would be nice if orion's volume level thing would be "global" aka. when I change the volume in kde it shows/affects in orion ...(1am, to tierd to remember the right words...sigh)

-----

```
inxi -xSCGAI
System:    Host: manjaro-pc Kernel: 4.9.8-1-MANJARO x86_64 (64 bit gcc: 6.3.1)
           Desktop: KDE Plasma 5.9.0 (Qt 5.8.0) Distro: Manjaro Linux
CPU:       Quad core Intel Core i5-6600K (-MCP-) cache: 6144 KB
           flags: (lm nx sse sse2 sse3 sse4_1 sse4_2 ssse3 vmx) bmips: 28040
           clock speeds: max: 4500 MHz 1: 4499 MHz 2: 4499 MHz 3: 4499 MHz 4: 4499 MHz
Graphics:  Card: NVIDIA GM204 [GeForce GTX 970] bus-ID: 01:00.0
           Display Server: X.Org 1.19.1 driver: nvidia Resolution: 1920x1080@60.00hz, 1920x1080@60.00hz
           GLX Renderer: GeForce GTX 970/PCIe/SSE2 GLX Version: 4.5.0 NVIDIA 375.26 Direct Rendering: Yes
Audio:     Card-1 NVIDIA GM204 High Definition Audio Controller driver: snd_hda_intel bus-ID: 01:00.1
           Card-2 Intel Sunrise Point-H HD Audio driver: snd_hda_intel bus-ID: 00:1f.3
           Sound: Advanced Linux Sound Architecture v: k4.9.8-1-MANJARO
Info:      Processes: 324 Uptime: 2 days Memory: 8744.3/15991.2MB Init: systemd Gcc sys: 6.3.1
           Client: Shell (bash 4.4.111) inxi: 2.3.8
```

**Comment by alamminsalo** [comment]
Can you tell me more specifically how to reproduce the problem? I tried it myself but only managed to affect volume by scrolling over the small floating player

**Comment by ahjolinna** [comment]
@alamminsalo : for example if I try scroll the chat down and when/if its already down then the volume lvl will go down....but this also happens when I scroll anywhere on the "video".... btw. I use qt-multimedia backend...(oh and I use the git version)

(I have this is same problem on my openSUSE/ultrabook)

**Comment by alamminsalo** [comment]
It's actually a feature added in [pull request](https://github.com/alamminsalo/orion/pull/31). But if it happens with the chat then I'll fix that out

**Comment by alamminsalo** [comment]
Fixed by moving the scroll feature inside volume button
