### ISSUE TITLE
top row icons unclear

### ISSUE THREAD

**Issue by rakslice** [alamminsalo/orion#55]
The top row icons (? / follow / chat) could use some tooltips to indicate what they are for; it's still not even clear to me what the left one does

**Comment by mroNNorm** [comment]
first one is enable/disable the miniplayer when you click something that's not player, but yeah it could probably use tooltips

**Comment by rakslice** [comment]
I started out to fix this, but didn't get very far; I was expecting it to be straighforward to set a simple floating tooltip, but it seems that Qt Quick doesn't have such a thing built-in other than on Buttons

**Comment by mroNNorm** [comment]
i know there is some code for hovering live streams to get a preview of what they're doing. You can probably look at that for an example. Also I'd probably just do something like 
Rectangle {
    width: some number
    height: some number
    Text {
        anchors.fill: parent
        text: "tooltip"
    }
}

**Comment by alamminsalo** [comment]
Fixed in [5f0d0a6](https://github.com/alamminsalo/orion/commit/5f0d0a664bf1b36057eb21e100c65ac13f2f9ffb)
