### ISSUE TITLE
no way to have chat show automatically

### ISSUE THREAD

**Issue by rakslice** [alamminsalo/orion#56]
When I switch to the playback view, chat is always closed, even if I previously had chat open. (The Twitch website remembers the previous setting). I generally want to see chat unless I explicitly close it, but I can understand that many users never want to see chat unless they explicitly open it. I would settle for a checkbox in the settings that makes chat open by default.

**Comment by mroNNorm** [comment]
hmm, seems like this is an issue witht he mini-player. it'll save it if there is no miniplayer. I think it's because the miniplayer will hide chat and never gets reset

**Comment by alamminsalo** [comment]
Fixed in [96a6553](https://github.com/alamminsalo/orion/commit/96a65535513e403cf5ae8cf116d1f5e1ea5aa89a)
