### ISSUE TITLE
video quality always resets to source

### ISSUE THREAD

**Issue by rakslice** [alamminsalo/orion#57]
When loading a new video stream, quality always switches back to source. On the Twitch website, the player uses the previous quality setting if transcodes are available for the current stream. A default quality selection in the settings would mostly serve the same purpose.

**Comment by alamminsalo** [comment]
I would rather not clutter settings with more options unless it's absolutely necessary. I'd suggest a simple fix of just attempting to use the same quality from previous stream, with source quality as fallback

**Comment by alamminsalo** [comment]
Fixed as suggested above

**Comment by rakslice** [comment]
Fixed in 510f3202009f2ecb604ed6c67ad56d88c011a8a
