### ISSUE TITLE
chat usernames are always shown in lower case

### ISSUE THREAD

**Issue by rakslice** [alamminsalo/orion#58]
The chat window shows all usernames in lower case, rather than in the user's configured capitalization.

FYI the capitalization is in the `display-name` tag (which may be absent or empty if a user has not changed the capitalization).  Tags are returned when the IRC client has enabled capability `:twitch.tv/tags`. See https://github.com/justintv/Twitch-API/blob/master/IRC.md#tags

**Comment by mroNNorm** [comment]
Yeah, That should be an easy fix, currenlty it grabs the name from some other place instead of display-name which probably has the correct capitalization.
