### ISSUE TITLE
Some channels with active streams don't show as live in followed channels screen

### ISSUE THREAD

**Issue by rakslice** [alamminsalo/orion#62]
I'm finding that channels sometimes show as offline in the followed channels list even when they are online and show as online in the search view if I search for them by name.  This behaviour seems to happen consistently for some channels I follow and not for others.

**Comment by rakslice** [comment]
The issue was that, in the case where multiple batches of streams requests were necessary (more than 50 channels followed), the final streams request for the final batch of channels wasn't being done.

**Comment by alamminsalo** [comment]
Duplication of [#13](https://github.com/alamminsalo/orion/issues/13).

Thanks for fixing this. It's been around for ages, but I couldn't find it (yet how obvious it was now thinking)
