### ISSUE TITLE
orion wont open (stays hidden) after latest git commits

### ISSUE THREAD

**Issue by ahjolinna** [alamminsalo/orion#64]
I just updated orion git build on my openSUSE system and it wont open anymore, it does run but wont open aka just stays hidden... I tried gdb and I didn't see any errors, here is [strace log](https://paste.kde.org/pv2dvdovy/4xveej/raw) ...I also even tried removing cache & confs to check if that was the problem..nope

system:

```
inxi -xSCGI
System:    Host: linux.suse Kernel: 4.4.49-16-default x86_64 (64 bit gcc: 4.8.5)                                                                                                                                                                   
           Desktop: KDE Plasma 5.9.2 (Qt 5.8.0) Distro: openSUSE Leap 42.2
CPU:       Quad core Intel Core i5-6600K (-MCP-) cache: 6144 KB
           flags: (lm nx sse sse2 sse3 sse4_1 sse4_2 ssse3 vmx) bmips: 28031
           clock speeds: max: 4500 MHz 1: 1007 MHz 2: 1052 MHz 3: 961 MHz 4: 839 MHz
Graphics:  Card: NVIDIA GM204 [GeForce GTX 970] bus-ID: 01:00.0
           Display Server: X.Org 1.19.3 driver: nvidia Resolution: 1920x1080@60.00hz, 1920x1080@60.00hz
           GLX Renderer: GeForce GTX 970/PCIe/SSE2 GLX Version: 4.5.0 NVIDIA 375.39 Direct Rendering: Yes
Info:      Processes: 324 Uptime: 17:40 Memory: 10986.8/15986.9MB Init: systemd runlevel: 5 Gcc sys: 4.8.5
           Client: Shell (bash 4.3.421) inxi: 2.3.8 
```

**Comment by alamminsalo** [comment]
Due to addition of tooltips to playerview the qt5-quickcontrols2 is now a dependency. Do you have this package installed?

**Comment by ahjolinna** [comment]
damn, I had added the normal qt5-quickcontrols ....I thought qt5.8 used v2 by default....oh well, this does mean that opensuse leap users have to add an extra repo to get it ...oh well, I really dont care as I will soon move to pure arch

**Comment by alamminsalo** [comment]
There's qt5-quickcontrols and qt5-quickcontrols2, they are separate packages

**Comment by ahjolinna** [comment]
I remember that v1 become EOL..... but maybe not yet
