### ISSUE TITLE
[linux] Latest commit breaks usability

### ISSUE THREAD

**Issue by XenonPK** [alamminsalo/orion#65]
Commits [5f0d0a6](https://github.com/alamminsalo/orion/commit/5ab994245b7e1226761147f88a38d00c353e64b7) onwards break usability on linux. 

The Package:
https://build.opensuse.org/package/show/home:xenonpk/orion

The builds are successful, and, after installation, I can see the icon in the tray, as well as the notifications (who is streaming, etc...), however, there is no window, and no way to interact with the program.

Using OpenSUSE Tumbleweed with KDE 5.9.2 and Qt 5.7.1

**Comment by mroNNorm** [comment]
actually it was the commit before it looks like, where he added a depends on qtquick.controls 2.1, so it seems like you'll need that for it to work again.

**Comment by XenonPK** [comment]
I've already added it to the build requirements, but the issue remains. In the commit you are talking about the window did not show, but if I right clicked on the tray and clicked on show/hide, it would appear.

**Comment by rakslice** [comment]
I took a look at openSUSE Tumbleweed 20170320 -- it doesn't have QtQuick.Controls 2.1, only 2.0. @XenonPK you'll want your spec file dependency to be `libqt5-qtquickcontrols2` rather than `libqt5-qtquickcontrols`

**Comment by rakslice** [comment]
Oh, I see, you've got `libqt5-qtquickcontrols2` in there conditionally already...

**Comment by alamminsalo** [comment]
Fixed

**Comment by XenonPK** [comment]
Confirmed working on Tumbleweed, unfortunately, while I have not tested it myself, people using LEAP 42.1 and 42.2 might have some issues getting this to work because qtquickcontrols2 is not available in their official repos.

In any case, It's available in the [Qt](https://software.opensuse.org/package/libqt5-qtquickcontrols2) development repo for them, so it just needs some additional elbow grease to get the dependencies.

Thanks for the pr , @rakslice !
