### ISSUE TITLE
Ability to search and follow games as well as streamers.

### ISSUE THREAD

**Issue by thoma5nator** [alamminsalo/orion#7]
Feature is on the android app for twitch but sadly rather archaic on the main site. Could it be a niche you could fill?

**Comment by alamminsalo** [comment]
Hey man and thanks for suggestion! Sounds cool but I would like to know more:

What do you mean by following a game? Do you mean a notification when a game's viewer count rises suddenly?

**Comment by thoma5nator** [comment]
On the mobile Twitch app at least, and on the main site in a kind of tucked-away capacity, you can search for and follow games, and they will appear in your Following list under your followed streamers.

**Comment by alamminsalo** [comment]
Okay so they'd appear under followed streams as a category in Followed view. Sounds good and would probably be a nice feature so people can easily search their favourite game's streams from there.

Also yeah, the games search functionality needs to be implemented. 

I'll add these features to future plans list.

**Comment by thoma5nator** [comment]
Cheers man!
