### ISSUE TITLE
Channels jump around in the Followed view

### ISSUE THREAD

**Issue by rakslice** [alamminsalo/orion#73]
Within the first few seconds after switching to the Followed view, channels jump around in the grid, leading to misclicks.  This is reproducible every time I switch to the Followed view, and happens even in the absence of any changes to the followed channel list or the online/offline status of any channels.

**Comment by rakslice** [comment]
This doesn't seem to affect Search, Featured, or Games grids.

**Comment by ahjolinna** [comment]
I haven't notice this issue on linux (openSUSE leap 42.2 +KDE)...this does remind me that I would like to have some sorting function

**Comment by rakslice** [comment]
This only occurs when following more than 25 channels (the boundary where more than one followed channel query is done to get all the followed channels).

FYI the sort order for favourite (followed) channels and featured channels is by viewer count. 

The issue I was seeing is due to multiple sets of stream results arriving for the same channels (potentially with differences in viewer count large enough to cause channels to rearrange).
