### ISSUE TITLE
Cannot paste password on mac

### ISSUE THREAD

**Issue by notQueen** [alamminsalo/orion#78]
Currently it is impossible to use cmd+v or right click > paste to insert password during login. I use a password management system where my password for twitch is 40 characters long.

As stated in the issue title I am using a Mac. Macbook Air, latest OS version if that helps in any way.

**Comment by rakslice** [comment]
Confirmed this issue in the release ver w/ El Capitan.

**Comment by rakslice** [comment]
Also note that, like mac, windows only shows a Copy context menu item and no Paste, although ctrl+v works there.

**Comment by rakslice** [comment]
This appears to be a build library version or packaging issue.

I just set up a dev env't on mac w/ a fresh QT 5.8 install, and a build of the current master branch from source with it gives working cmd+v in the auth webview.

**Comment by rakslice** [comment]
I have a branch that adds custom a context menu to the auth page with Paste and friends, but it uses `WebEngineView.contextMenuRequested` which is new in QtWebEngine 1.4, and as long as cmd-v works instead I'm not in a hurry to break Qt 5.6 support

**Comment by alamminsalo** [comment]
I think the correct way to go here is to dump the webengineview altogether and move to starting a simple webserver instance which listens to auth callback request to localhost page

**Comment by rakslice** [comment]
The switch to using a regular web browser for auth f37b2e6a0eb902fc8acaaa0f59099ee1a148623d should address this issue

**Comment by ahjolinna** [comment]
is this issue still relevant ? can this be closed?

**Comment by notQueen** [comment]
I would download the app to test but I can't find any newer version than from January. If someone could point me in the right direction I'll be happy to test

**Comment by ahjolinna** [comment]
oh yeah It seems mac version was missing from 1.5.1-rc, maybe @alamminsalo could release "rc2" soon'ish with mac version included?

**Comment by alamminsalo** [comment]
Just put up mac release:
https://github.com/alamminsalo/orion/releases/tag/v1.6.1
