### ISSUE TITLE
Adding Twitch Chat Suggestion

### ISSUE THREAD

**Issue by hakuame** [alamminsalo/orion#8]
Is it possible there will be twitch chat adding to the application in the future?
I really like this app, adding chat to it will make it perfect!

**Comment by alamminsalo** [comment]
It is on my to-do list. The twitch chat is basically irc client AFAIK, so it shouldn't be very hard to implement once I get down to it. But it could take a few months or so

**Comment by GhettoGirl** [comment]
May I suggest you this Qt library for IRC chat, if you don't know about it already :smile: 
https://github.com/communi/libcommuni

> Communi provides a set of tools for enabling IRC connectivity in Qt-based C++ and QML applications. See the online reference documentation for help with getting started.

**Comment by alamminsalo** [comment]
Yes, that was the library I was also looking onto 👍

**Comment by alamminsalo** [comment]
Twitch chat has been added to application, I will update the installers when I have the time
