### ISSUE TITLE
 orion wont build on opensuse leap 42.2 / Qt5.6

### ISSUE THREAD

**Issue by ahjolinna** [alamminsalo/orion#83]
after latest changes in [orion](https://build.opensuse.org/package/show/home:ahjolinna/orion) it wont build on opensuse 42.2 anymore but it will build on tumbleweed, this seem to be caused by the Qt version? (5.6.x LTS vs 5.8)

here is the log file: 
[orion build log leap 42.2.txt](https://github.com/alamminsalo/orion/files/919936/orion.build.log.leap.42.2.txt)

**Comment by ahjolinna** [comment]
@rakslice @alamminsalo : I don't know if the new "badges" feature can be fixed to build against Qt5.6.x I think it could be done as this feature does work on SailfishOS twitch app and it uses Qt5.6...but then again implementation may differ too much. If this can't be fixed then it would suck but what can you do.

Anyway I also think it would be good time to release a new "stable" version, 1.4 was end of January and there has been many changes since then.

**Comment by rakslice** [comment]
FYI I don't know if this results in builds that actually work in QT 5.6, but it gets through the build at any rate

**Comment by ahjolinna** [comment]
I have tested that patch and it works ...so closing
