### ISSUE TITLE
running orion on osx

### ISSUE THREAD

**Issue by jademcgough** [alamminsalo/orion#9]
Been kind of a slog trying to figure out dependencies. I got `libmpv` installed, but the application is still failing with the following message:

```
Dyld Error Message:
  Library not loaded: @rpath/QtOpenGL.framework/Versions/5/QtOpenGL
  Referenced from: /Volumes/VOLUME/Orion.app/Contents/MacOS/orion
  Reason: image not found
```

I did an install of `qt5`, which didn't resolve the issue. What else am I missing :\

**Comment by alamminsalo** [comment]
Hello, I've just uploaded a new mac package which hopefully resolves the issue: [1.2.0-dmg](https://github.com/alamminsalo/orion/releases/download/1.2.0/orion-1.2.dmg)

Cheers

**Comment by Coriou** [comment]
v1.3.0 works like a charm on macOS for me. Awesome job, love it ! Thanks :)

**Comment by b3visund3ad** [comment]
I can not seem to get channel vods working.
