### ISSUE TITLE
need basic network error messages

### ISSUE THREAD

**Issue by rakslice** [alamminsalo/orion#97]
a literal "something is wrong with the network" message in the case of basic network failures would be better than nothing at all

**Comment by alamminsalo** [comment]
There should be a orange dropdown box that becomes visible when network goes down. See Views.connectionErrorRectangle qml

**Comment by rakslice** [comment]
ah, I'd never seen it because it didn't show up if there is a problem at startup.

**Comment by rakslice** [comment]
(see https://github.com/alamminsalo/orion/pull/102)
